#+Title: Logic and Proof
#+Author: [[http://www.andrew.cmu.edu/user/avigad][Jeremy Avigad]]

* Introduction

** About Lean

The /Lean/ project was launched by Leonardo de Moura at Microsoft
Research Redmond in 2012. It is an ongoing, long-term effort, and
much of the potential for automation will be realized only gradually
over time. Lean is released under the Apache 2.0 license, a permissive
open source license that permits others to use and extend the code and
mathematical libraries freely.

There are currently two ways to use Lean. The first is to run it from
the web: a Javascript version of Lean, a standard library of
definitions and theorems, and an editor are actually downloaded to
your browser and run there. This provides a quick and convenient way to
begin experimenting with the system.

The second way to use Lean is to install and run it natively on your
computer. The native version is much faster than the web version, and
is more flexible in other ways, too. It comes with an Emacs mode that
offers powerful support for writing and debugging proofs, and is much
better suited for serious use.

** LaTeX Examples

*** Proof Trees

\begin{prooftree}
\AxiomC{$A \lor B$}
\AxiomC{[$A$]}
\noLine
\UnaryInfC{$C$}
\AxiomC{[$B$]}
\noLine
\UnaryInfC{$C$}
\TrinaryInfC{$C$}
\end{prooftree}

*** align environment

\begin{align*}
\sin A \cos B &= \frac{1}{2}\left[ \sin(A-B)+\sin(A+B) \right] \\
\sin A \sin B &= \frac{1}{2}\left[ \sin(A-B)-\cos(A+B) \right] \\
\cos A \cos B &= \frac{1}{2}\left[ \cos(A-B)+\cos(A+B) \right] \\
\end{align*}
