#+Title: Logic and Proof
#+Author: [[http://www.andrew.cmu.edu/user/avigad][Jeremy Avigad]], [[http://www.andrew.cmu.edu/user/rlewis1/][Robert Y. Lewis]],  [[http://www.contrib.andrew.cmu.edu/~fpv/][Floris van Doorn]]

* First Order Logic
:PROPERTIES:
  :CUSTOM_ID: First_Order_Logic
:END:      

Propositional logic provides a good start at describing the general
principles of logical reasoning, but it does not go far enough. Some
of the limitations are apparent even in the "Malice and Alice" example
from Chapter [[file:02_Propositional_Logic.org::#Propositional_Logic][Propositional Logic]]. Propositional logic does not give us
the means to express a general principle that tells us that if Alice
is with her son on the beach, then her son is with Alice; the general
fact that no child is younger than his or her parent; or the general
fact that if someone is alone, they are not with someone else. To
express principles like these, we need a way to talk about objects and
individuals, as well as their properties and the relationships between
them. These are exactly what is provided by a more expressive logical
framework known as /first-order logic/, which will be the topic of
the next few chapters.

** Functions, Predicates, and Relations
:PROPERTIES:
  :CUSTOM_ID: Functions_Predicates_and_Relations
:END:      

Consider some ordinary statements about the natural numbers:
- Every natural number is even or odd, but not both.
- A natural number is even if and only if it is divisible by two.
- If some natural number, $x$, is even, then so is $x^2$.
- A natural number $x$ is even if and only if $x + 1$ is odd.
- Any prime number that is greater than 2 is odd.
- For any three natural numbers $x$, $y$, and $z$, if $x$ divides $y$
  and $y$ divides $z$, then $x$ divides $z$.
These statements are true, but we generally do not think of them as
/logically valid/: they depend on assumptions about the natural
numbers, the meaning of the terms "even" and "odd," and so on. But
once we accept the first statement, for example, it seems to be a
logical consequence that the number of stairs in the White House is
either even or odd, and, in particular, if it is not even, it is
odd. To make sense of inferences like these, we need a logical system
that can deal with objects, their properties, and relations between
them.

Rather than fix a single language once and for all, first-order logic
allows us to specify the symbols we wish to use for any given domain
of interest. In this section, we will use the following running
example:
- the domain of interest is the natural numbers, $\mathbb{N}$.
- there are objects, $0$, $1$, $2$, $3$, ....
- there are functions, addition and multiplication, as well as the
  square function, on this domain.
- there are predicates on this domain, "even," "odd," and "prime."
- there are relations between elements of this domain, "equal," "less
  than", and "divides."
For our logical language, we will choose symbols 1, 2, 3,
$\fn{add}$, $\fn{mul}$, $\fn{square}$, $\fn{even}$, $\fn{odd}$, $\fn{prime}$,
$\fn{lt}$, and so on, to denote these things. We will also have
variables $x$, $y$, and $z$ ranging over the natural numbers. Note all
of the following.
- Functions can take any number of arguments: if $x$ and $y$ are
  natural numbers, it makes sense to write $\fn{mul}(x, y)$ and
  $\fn{square}(x)$. so $\fn{mul}$ takes two arguments, and
  $\fn{square}$ takes only one.
- Predicates and relations can also be understood in these terms. The
  predicates $\fn{even}(x)$ and $\fn{prime}(x)$ take one argument,
  while the binary relations $\fn{divides}(x, y)$ and $\fn{lt}(x,y)$
  take two arguments.
- Functions are different from predicates! A function takes one or
  more arguments, and returns a /value/. A predicate takes one or more
  arguments, and is either true or false. We can think of predicates
  as returning propositions, rather than values.
- In fact, we can think of the constant symbols $1, 2, 3, \ldots$ as
  special sorts of function symbols that take zero
  arguments. Analogously, we can consider the predicates that take
  zero arguments to be the constant logical values, $\top$ and $\bot$.
- In ordinary mathematics, we often use "infix" notation for binary
  functions and relations. For example, we usually write $x \times y$
  or $x \cdot y$ instead of $\fn{mul}(x, y)$, and we write $x < y$
  instead of $\fn{lt}(x, y)$. We will use these conventions when
  writing proofs in natural deduction, and they are supported in Lean
  as well.
- We will treat the equality relation, $x = y$, as a special binary
  relation that is included in every first-order language.

First-order logic allows us to build complex expressions out of the
basic ones. Starting with the variables and constants, we can use the
function symbols to build up compound expressions like these:
\begin{equation*}
x + y + z, \quad (x + 1) \times y \times y, \quad \fn{square} (x + y \times z)
\end{equation*}
Such expressions are called "terms." Intuitively, they name objects
in the intended domain of discourse.

Now, using the predicates and relation symbols, we can make assertions
about these expressions:
\begin{equation*}
\fn{even}(x + y + z), \quad \fn{prime}((x + 1) \times y \times y), \quad
\fn{square} (x + y \times z) = w, \quad x + y < z
\end{equation*}
Even more interestingly, we can use propositional connectives to build
compound expressions like these:
- $\fn{even}(x + y + z) \wedge \fn{prime}((x + 1) \times y \times y)$
- $\neg (\fn{square} (x + y \times z) = w) \vee x + y < z$
- $x < y \wedge \fn{even}(x) \wedge \fn{even}(y) \to x + 1 < y$
The second one, for example, asserts that either $(x + yz)^2$ is not
equal to $w$, or $x + y$ is less than $z$. Remember, these are
expressions in symbolic logic; in ordinary mathematics, we would
express the notions using words like "is even" and "if and only if,"
as we did above. We will use notation like this whenever we are in the
realm of symbolic logic, for example, when we write proofs in natural
deduction. Expressions like these are called /formulas/. In contrast
to terms, which name things, formulas /say things/; in other words, they
make assertions about objects in the domain of discourse.

** The Universal Quantifier

What makes first-order logic powerful is that it allows us to make
general assertions using /quantifiers/. The universal quantifier
$\forall$ followed by a variable $x$ is meant to represent the phrase
"for every $x$." In other words, it asserts that every value of $x$
has the property that follows it. Using the universal quantifier, the
examples with which we began this previous section can be expressed as
follows:
\begin{itemize}
\item $\fa x ((\fn{even}(x) \vee \fn{odd}(x)) \wedge \neg
(\fn{even}(x) \wedge \neg \fn{odd}(x)))$.
\item $\fa x (\fn{even}(x) \liff 2 \mid x)$
\item $\fa x (\fn{even}(x) \to \fn{even}(x^2))$
\item $\fa x (\fn{even}(x) \liff 2 \odd{x+1})$
\item $\fa x (\fn{prime}(x) \wedge x > 2 \to \fn{odd}(x))$
\item $\fa x \fa y \fa z (x \mid y \wedge y \mid z \to x \mid z)$
\end{itemize}
It is common to combine multiple quantifiers of the same kind, and
write, for example, $\fa {x, y, z} (x \mid y \wedge y \mid z
\to x \mid z)$ in the last expression.

Here are some notes on syntax:
- In symbolic logic, the universal quantifier is usually taken to bind
  tightly. For example, $\fa x P \vee Q$ is interpreted as $(\fa x P)
  \vee Q$, and we would write $\fa x (P \vee Q)$ to extend the scope.
- Be careful, however. In other contexts, especially in computer
  science, people often give quantifiers the /widest/ scope
  possible. This is the case with Lean. For example, =∀ x, P ∨ Q= is
  interpreted as =∀ x, (P ∨ Q)=, and we would write =(∀ x, P) ∨ Q= to
  limit the scope.
- After the quantifier $\forall x$, the variable $x$ is /bound/. For
  example, the expression $\fa x (\fn{even}(x) \vee \fn{odd}(x))$ is
  expresses that every number is even or odd. Notice that the variable
  $x$ does not appear anywhere in the informal statement. The
  statement is not about $x$ at all; rather $x$ is a dummy variable, a
  placeholder that stands for the "thing" referred to within a phrase
  that beings with the words "every thing." We think of the expression 
  $\fa x (\fn{even}(x) \vee \fn{odd}(x))$ as being the same as the
  expression $\fa y (\fn{even}(y) \vee \fn{odd}(y))$. Lean treats
  these expressions as the same as well.
- The expression =∀ x y z, x ∣ y → y ∣ z → x ∣ z= is interpreted as =∀
  x y z, x ∣ y → (y ∣ z → x ∣ z)=, with parentheses associated to the
  /right/. The part of the expression after the universal quantifier
  can therefore be interpreted as saying "given that =x= divides =y=
  and that =y= divides =z=, =x= divides =z=." The expression is
  logically equivalent to =∀ x y z, x ∣ y ∧ y ∣ z → x ∣ z=, but we
  will see that, in Lean, it is often convenient to express facts like
  this as an iterated implication.

A variable that is not bound is called /free/. Notice that formulas in
first-order logic say things about their free variables. For example,
in the interpretation we have in mind, the formula $\fa y (x \le y)$
says that $x$ is less than or equal to every natural number. The
formula $\fa z (x \le z)$ says exactly the same thing; we can always
rename a bound variable, as long as we pick a name that does not clash
with another name that is already in use. On the other hand, the
formula $\fa y (w \le y)$ says that $w$ is less than or equal to every
natural number. This is an entirely different statement: it says
something about $w$, rather than $x$. So renaming a /free/ variable
changes the meaning of a formula.

Notice also that some formulas, like $\fa {x, y} (x \le y \vee y \le
x)$, have no free variables at all. Such a formula is called a
/sentence/, because it makes an outright assertion, a statement that
is either true or false about the intended interpretation. In Chapter
[[file:10_Semantics_of_First_Order_Logic::#Semantics_of_First_Order_Logic][Semantics of First Order Logic]], we will make the notion of an
"intended interpretation" precise, and explain what it means to be
"true in an interpretation." For now, the idea that formulas say
things about about object in an intended interpretation should
motivate the rules for reasoning with such expressions.

In Chapter [[file:01_Introduction.org::#Introduction][Introduction]] we proved that the square root of two is
irrational. One way to construe the statement is as follows:
#+BEGIN_QUOTE
For every pair of natural numbers, $a$ and $b$, it is not the case
that $a^2 = 2 b^2$.
#+END_QUOTE
The advantage of this formulation is that we can restrict our
attention to the natural numbers, without having to consider the
larger domain of rationals. In symbolic logic, assuming our intended
domain of discourse is the natural numbers, we would express this
theorem using the universal quantifier:
\begin{equation*}
\fa {a, b} \neg (a^2 = 2 b^2). 
\end{equation*}
How do we prove such a theorem? Informally, we would use such a
pattern:
#+BEGIN_QUOTE
Let $a$ and $b$ be arbitrary integers, and suppose $a^2 = 2 b^2$.

...

Contradiction.
#+END_QUOTE
What we are really doing is proving that the universal statement
holds, by showing that it holds of "arbitrary" values $a$ and $b$. In
natural deduction, the proof would look something like this:
\begin{center}
\AXM{}
\RLM{1}
\UIM{a^2 = 2 \times b^2}
\UIM{\vdots}
\UIM{\bot}
\RLM{1}
\UIM{\neg (a^2 = 2 \times b^2)}
\UIM{\fa b \neg (a^2 = 2 \times b^2)}
\UIM{\fa a \fa b \neg (a^2 = 2 \times b^2)}
\DP
\end{center}
Notice that after the hypothesis is canceled, we have proved $\neg
(a^2 = 2 \times b^2)$ without making any assumptions about $a$ and
$b$; at this stage in the proof, they are "arbitrary," justifying the
application of the universal quantifiers in the next two rules.

This example motivates the following rule in natural deduction:
\begin{prooftree}
\AXM{A(x)}
\UIM{\fa x A(x)}
\end{prooftree}
provided $x$ is not free in any uncanceled hypothesis. Here $A(x)$
stands for any formula that (potentially) mentions $x$. Also remember
that if $y$ is any "fresh" variable that does not occur in $A$, we are
thinking of $\fa x A(x)$ as being the same as $\fa y A(y)$.

What about the elimination rule? Suppose we know that every number is
even or odd. Then, in an ordinary proof, we are free to assert "$a$ is
even or $a$ is odd," or "$a^2$ is even or $a^2$ is odd." In terms of
symbolic logic, this amounts to the following inference: from $\fa x
(\fn{even}(x) \vee \fn{odd}(x))$, we can conclude $\fn{even}(t) \vee
\fn{odd}(t)$ for any term $t$. This motivates the elimination rule for
the universal quantifier:
\begin{prooftree}
\AXM{\fa x A(x)}
\UIM{A(t)}
\end{prooftree}
where $t$ is an arbitrary term. 

In a sense, this feels like the elimination rule for implication; we
might read the hypothesis as saying "if $x$ is any thing, then $x$ is
even or odd." The conclusion is obtained by applying it to the fact
that $n$ is a thing. Note that, in general, we could replace $n$ by
any /term/ in the language, like $n (m + 5) +2$. Similarly, the
introduction rule feels like the introduction rule for implication. If
we want to show that everything has a certain property, we temporarily
let $x$ denote an arbitrary thing, and then show that it has the
relevant property.

** The Existential Quantifier

Dual to the universal quantifier is the existential quantifier,
$\exists$, which is used to express assertions such as "some number is
even," or, "between any two even numbers there is an odd number." 

The following statements about the natural numbers assert the
existence of some natural number:
- There exists an odd composite number. (Remember that a natural
  number is /composite/ if it is greater than 1 and not prime.)
- Every natural number greater than one has a prime divisor.
- For every $n$, if $n$ has a prime divisor smaller than $n$, then $n$
  is composite.

These statements can be expressed in first-order logic using the
existential quantifier as follows:

- $\ex n (\fn{odd}(n) \wedge \fn{composite}(n))$
- $\fa n (n > 1 \to \ex p (\fn{prime}(p) \wedge p \mid n))$
- $\fa n ((\ex p (p \mid n \wedge \fn{prime}(p) \wedge p < n)) \to
  \fn{composite}(n))$

After we write $\exists \; n$, the variable $n$ is bound in the
formula, just as for the universal quantifier. So the formulas $\ex n
\fn{composite}(n)$ and $\ex m \fn{composite}(m)$ are considered the
same.

How do we prove such existential statements? Suppose we want to prove
that there exists an odd composite number. To do this, we just present
a candidate, and show that the candidate satisfies the required
properties. For example, we could choose 15, and then show that 15 is
odd and that 15 is prime. Of course, there's nothing special about 15,
and we could have proven it also using a different number, like 9
or 35. The choice of candidate does not matter, as long as it has the
required property.

In a natural deduction proof this would look like this:
\begin{center}
\AXM{\vdots}
\UIM{\fn{odd}(15)\wedge\fn{composite}(15)}
\UIM{\ex n(\fn{odd}(n)\wedge\fn{composite}(n))}
\DP
\end{center}
This illustrates the introduction rule for the existential quantifier:
\begin{center}
\AXM{A(t)}
\UIM{\ex x A(x)}
\DP
\end{center}
where $t$ is any term. So to prove an existential formula, we just
have to give one particular term for which we can prove that
formula. Such term is called a /witness/ for the formula.

What about the elimination rule? Suppose that we know that $n$ is some
natural number and we know that there exists a prime $p$ such that $p
< n$ and $p \mid n$. How can we use this to prove that $n$ is
composite? We can reason as follows:
#+BEGIN_QUOTE
Let $p$ be any prime such that $p < n$ and $p \mid n$. 

...

Therefore, $n$ is composite.
#+END_QUOTE
First, we assume that there is some $p$ which satisfies the properties
$p$ is prime, $p < n$ and $p \mid n$, and then we reason about that
$p$. As with case-based reasoning using "or," the assumption is only
temporary: if we can show that $n$ is composite from that assumption,
that we have essentially shown that $n$ is composite assuming the
existence of such a $p$. Notice that in this pattern of reasoning, $p$
should be "arbitrary." In other words, we should not have assumed
anything about $p$ beforehand, we should not make any additional
assumptions about $p$ along the way, and the conclusion should not
mention $p$. Only then does it makes sense to say that the conclusion
follows from the "mere" existence of a $p$ with the assumed
properties.

In natural deduction, the elimination rule is expressed as follows:
\begin{prooftree}
\AXM{\ex x A(x)}
\AXM{}
\RLM{1}
\UIM{A(y)}
\UIM{\vdots}
\UIM{B}
\RLM{1}
\BIM{B}
\end{prooftree}
Here we require that $y$ is not free in $B$, and that the only
uncanceled hypotheses where $y$ occurs freely are the hypotheses
$A(y)$ that are canceled when you apply this rule. Formally, this is
what it means to say that $y$ is "arbitrary." As was the case for or
elimination and implication introduction, you can use the hypothesis
$A(y)$ multiple times in the proof of $B$, and cancel all of them at
once.

Intuitively, the rule says that you can prove $B$ from the assumption
$\ex x A(x)$ by assuming $A(y)$ for a fresh variable $y$, and
concluding, in any number of steps, that $B$ follows. You should
compare this rule to the rule for or elimination, which is somewhat
analogous. In the following example, we show that if $A(x)$ always
implies $\neg B(x)$, then there cannot be an $x$ for which both $A(x)$
and $B(x)$ holds.

** Relativization and Sorts
:PROPERTIES:
  :CUSTOM_ID: Relativization_and_Sorts
:END:      

In first-order logic as we have presented it, there is one intended
"universe" of objects of discourse, and the universal and existential
quantifiers range over that universe. For example, we could design a
language to talk about people living in a certain town, with a
relation $\fn{loves}(x, y)$ to express that $x$ loves $y$. In such a
language, we might express the statement that "everyone loves someone"
by writing $\fa x \ex y \fn{loves}(x, y)$.

You should keep in mind that, at this stage, $\fn{loves}$ is just a
symbol. We have designed the language with a certain interpretation in
mind, but one could also interpret the language as making statements
about the natural numbers, where $\fn{loves}(x, y)$ means that $x$ is
less than or equal to $y$. In that interpretation, the sentence
\begin{equation*}
\fa {x, y, z} (\fn{loves}(x, y) \wedge \fn{loves}(y, z) \to
\fn{loves}(x, z))
\end{equation*}
is true, though in the original interpretation it makes an implausible
claim about the nature of love triangles. In Chapter [[file:10_Semantics_of_First_Order_Logic.org::#Semantics_of_First_Order_Logic][Semantics of
First Order Logic]], we will spell out the notion that the deductive
rules of first-order logic enable us to determine the statements that
are true in \emph{all} interpretations, just as the rules of
propositional logic enable us to determine the statements that are
true under all truth assignments.

Returning to the original example, suppose we want to represent the
statement that, in our town, all the women are strong and all the men
are good looking. We could do that with the following two sentences:
- $\fa x (\fn{woman}(x) \to \fn{strong}(x))$
- $\fa x (\fn{man}(x) \to \fn{good{\dash}looking}(x))$
These are instances of /relativization/. The universal quantifier
ranges over all the people in the town, but this device gives us a way
of using implication to restrict the scope of our statements to men
and women, respectively. The trick also comes into play when we render
"every prime number greater than two is odd":
\begin{equation*}
\fa x (\fn{prime}(x) \wedge x \ge 2 \to \fn{odd}(x)).
\end{equation*}
We could also read this more literally as saying "for every number
$x$, if $x$ is prime and $x$ is greater than or equal to 2, then $x$
is odd," but it is natural to read it as a restricted quantifier. 

It is also possible to relativize the existential quantifier to say
things like "some woman is strong" and "some man is good-looking."
These are expressed as follows:
- $\ex x (\fn{woman}(x) \wedge \fn{strong}(x))$
- $\ex x (\fn{man}(x) \wedge \fn{good{\dash}looking}(x))$
Notice that although we used implication to relativize the universal
quantifier, here we need to use conjunction instead of
implication. The expression $\ex x (\fn{woman}(x) \to \fn{strong}(x))$
says that there is something with the property that if it is a woman,
then it is strong. Classically this is equivalent to saying that there
is something which is either not a woman or is strong, which is a
funny thing to say.

Now, suppose we are studying geometry, and we want to express the fact
that given any two distinct points $p$ and $q$ and any two lines $L$
and $M$, if $L$ and $M$ both pass through $p$ and $q$, then they have
to be the same. (In other words, there is at most one line between two
distinct points.) One option is to design a first-order logic where the
intended universe is big enough to include both points and lines, and
use relativization:
\begin{multline*}
\fa {p, q, L, M} (\fn{point}(p) \wedge \fn{point}(q) \wedge
\fn{line}(L) \wedge \fn{line}(M) \\
\wedge \fn{on}(p,L) \wedge \fn{on}(q,L) \wedge \fn{on}(p,M) \wedge
\fn{on}(q,M) \to L = M)
\end{multline*}
But dealing with such predicates is tedious, and there is a mild
extension of first-order logic, called /many-sorted first-order
logic/, which builds in some of the bookkeeping. In many-sorted logic,
one can have different sorts of objects --- such as points and lines
--- and a separate stock of variables and quantifiers ranging over
each. Moreover, the specification of function symbols and predicate
symbols indicates what sorts of arguments they expect, and, in the
case of function symbols, what sort of argument they return. For
example, we might choose to have a sort with variables $p, q, r,
\ldots$ ranging over points, a sort with variables $L, M, N, \ldots$
ranging over lines, and a relation $\fn{on}(p, L)$ relating the
two. Then the assertion above is rendered more simply as follows:
\begin{equation*}
\fa {p, q, L, M} (\fn{on}(p,L) \wedge \fn{on}(q,L) \wedge \fn{on}(p,M) \wedge
\fn{on}(q,M) \to L = M)
\end{equation*}

** Equality

In symbolic logic, we use the expression $s = t$ to express the fact
that $s$ and $t$ are "equal" or "identical." The equality symbol is
meant to model what we mean when we say, for example, "Alice's brother
is the victim," or "2 + 2 = 4." We are asserting that two different
descriptions refer to the same object. Because the notion of identity
can be applied to virtually any domain of objects, it is viewed as
falling under the province of logic.

Talk of "equality" or "identity" raises messy philosophical questions,
however. Am I the same person I was three days ago? Are the two copies
of /Huckleberry Finn/ sitting on my shelf the same book, or two
different books? Using symbolic logic to model identity presupposes
that we have in mind a certain way of carving up and interpreting the
world. We assume that our terms refer to distinct entities, and
writing $s = t$ asserts that the two expressions refer to the same
thing. Axiomatically, we assume that equality satisfies the following
three properties:
- /reflexivity/: $t = t$, for any term $t$
- /symmetry/: if $s = t$, then $t = s$
- /transitivity/: if $r = s$ and $s = t$, then $r = t$.

These properties are not enough to characterize equality, however. If
two expressions denote the same thing, then we should be able to
subtitute one for any other in any expression. It is convenient to
adopt the following convention: if $r$ is any term, we may write
$r(x)$ to indicate that the variable $x$ may occur in $r$. Then, if
$s$ is another term, we can thereafter write $r(s)$ to denote the
result of replacing $s$ for $x$ in $r$. The substition rule for terms
thus reads as follows: if $s = t$, then $r(s) = r(t)$. 

We already adopted a similiar convention for formulas: if we introduce
a formula as $A(x)$, then $A(t)$ denotes the result of substituting
$t$ for $x$ in $A$. With this in mind, we can write the rules for
equality as follows:
\begin{center}
\AXM{}
\UIM{t = t}
\DP
\quad
\AXM{s = t}
\UIM{t = s}
\DP
\quad
\AXM{r = s}
\AXM{s = t}
\BIM{r = t}
\DP
\\
\ \\
\AXM{s = t}
\UIM{r(s) = r(t)}
\DP
\quad
\AXM{s = t}
\AXM{P(s)}
\BIM{P(t)}
\DP
\end{center}
In the next chapter, you will learn how to use them.

Using equality, we can define even more quantifiers.

- We can express "there are at least two elements $x$ such that $A(x)$
  holds" as $\ex x \ex y (x \neq y \wedge A(x) \wedge A(y))$.

- We can express "there are at most two elements $x$ such that $A(x)$
  holds" as $\fa x \fa y \fa z (A(x) \wedge A(y) \wedge A(z) \to x = y
  \vee y = z \vee x = z)$. This states that if we have three elements
  $a$ for which $A(a)$ holds, then two of them must be equal.

- We can express "there are exactly two elements $x$ such that $A(x)$
  holds" as the conjunction of the above two statements.

As an exercise, write out in first order logic the statements that
there are at least, at most, and exactly three elements $x$ such that
$A(x)$ holds.

In logic, the expression $\exists!x \; A(x)$ is used to express the
fact that there is a /unique/ $x$ satisfying $A(x)$, which is to say,
there is exactly one such $x$. As above, this can be expressed as
follows:
\begin{equation*}
\ex x A(x) \wedge \fa y \fa {y'} (A(y) \wedge A(y') \to y = y')
\end{equation*}
The first conjunct says that there is at least one object satisfying
$A$, and the second conjunct says that there is at most one. The same
thing can be expressed more concisely as follows:
\begin{equation*}
\ex x (A(x) \wedge \fa y (A(y) \to y = x))
\end{equation*}
You should think about why this second expression works. In the next
chapter we will see that, using the rules of natural deduction, we can prove
that these two expressions are equivalent.

** Exercises

1. A /perfect number/ is a number that is equal to the sum of its
   proper divisors, that is, the numbers that divide it, other than
   itself. For example, 6 is perfect, because $6 = 1 + 2 + 3$.

   Using a language with variables ranging over the natural numbers and
   suitable functions and predicates, write down first-order sentences
   asserting the following. Use a predicate $\fn{perfect}$ to express
   that a number is perfect.

   - 28 is perfect.

   - There are no perfect numbers between 100 and 200.

   - There are (at least) two perfect numbers between 200 and 10,000.
     (Express this by saying that there are perfect numbers $x$ and
     $y$ between 200 and 10,000, with the property that $x \neq y$.)

   - Every perfect number is even.

   - For every number, there is a perfect number that is larger than
     it. (This is one way to express the statement that there are
     infinitely many perfect numbers.)

   Here, the phrase ``between $a$ and $b$ '' is meant to include $a$
   and $b$.

   By the way, we do not know whether the last two statements are
   true. They are open questions.

2. Using a language with variables ranging over people and suitable
   predicates, write down first-order sentences asserting the
   following:

   - Nobody trusts a politician.
   - Anyone who trusts a politician is crazy.
   - Everyone knows someone who is related to a politician.
   - Everyone who is rich is either a politician or knows a politician.

   In each case, some interpretation may be involved. Notice that
   writing down a logical expression is one way of helping to clarify
   the meaning.


