#+Title: Logic and Proof
#+Author: [[http://www.andrew.cmu.edu/user/avigad][Jeremy Avigad]], [[http://www.andrew.cmu.edu/user/rlewis1/][Robert Y. Lewis]],  [[http://www.contrib.andrew.cmu.edu/~fpv/][Floris van Doorn]]

* Natural Deduction for First Order Logic
:PROPERTIES:
  :CUSTOM_ID: Natural_Deduction_for_First_Order_Logic
:END:      

** Rules of Inference

In the last chapter, we discussed the language of first-order logic,
and the rules that govern their use. We summarize them here:

*** Universal quantifier

\begin{quote}
\AXM{A(x)}
\RLM{\mathord{\forall}\mathrm{I}}
\UIM{\fa y A(y)}
\DP
\quad\quad
\AXM{\fa x A(x)}
\RLM{\mathord{\forall}\mathrm{E}}
\UIM{A(t)}
\DP
\end{quote}
In the introduction rule, $x$ should not be free in any uncanceled
hypothesis. In the elimination rule, $t$ can be any term that does not
clash with any of the bound variables in $A$.

*** Existential quantifier

\begin{quote}
\AXM{A(t)}
\RLM{\mathord{\exists}\mathrm{I}}
\UIM{\ex x A(x)}
\DP
\quad\quad
\AXM{\ex x A(x)}
\AXM{}
\RLM{1}
\UIM{A(y)}
\noLine
\UIM{\vdots}
\noLine
\UIM{B}
\RLM{1 \;\; \mathord{\exists}\mathrm{E}}
\BIM{B}
\DP
\end{quote}
In the introduction rule, $t$ cant be any term that does not clash
with any of the bound variables in $A$. In the elimination rule, $y$
should not be free in $B$ or any uncanceled hypothesis.

*** Equality

\begin{center}
\AXM{}
\RLM{\mathrm{refl}}
\UIM{t = t}
\DP
\quad
\AXM{s = t}
\RLM{\mathrm{symm}}
\UIM{t = s}
\DP
\quad
\AXM{r = s}
\AXM{s = t}
\RLM{\mathrm{trans}}
\BIM{r = t}
\DP
\\
\ \\
\AXM{s = t}
\RLM{\mathrm{subst}}
\UIM{r(s) = r(t)}
\DP
\quad
\AXM{s = t}
\RLM{\mathrm{subst}}
\AXM{P(s)}
\BIM{P(t)}
\DP
\end{center}
Strictly speaking, only $\mathrm{refl}$ and the second substitution
rule are necessary. The others can be derived from them.

** The Universal Quantifier

The following example of a proof in natural deduction shows that if,
for every $x$, $A(x)$ holds, and for every $x$, $B(x)$ holds, then for
every $x$, they both hold:
\begin{prooftree}
\AXM{}
\RLM{1}
\UIM{\fa x A(x)}
\UIM{A(y)}
\AXM{}
\RLM{2}
\UIM{\fa x B(x)}
\UIM{B(y)}
\BIM{A(y) \wedge B(y)}
\UIM{\fa y (A(y) \wedge B(y))}
\RLM{2}
\UIM{\fa x B(x) \to \fa y (A(y) \wedge B(y))}
\RLM{1}
\UIM{\fa x A(x) \to (\fa x B(x) \to \fa y (A(y) \wedge B(y)))}
\end{prooftree}
Notice that neither of the assumptions 1 or 2 mention $y$, so
that $y$ is really "arbitrary" at the point where the universal
quantifiers are introduced.

As an exercise, try proving the converse:
\begin{equation*}
(\fa x (A(x) \to B(x))) \to (\fa x A(x) \to \fa x B(x)).
\end{equation*}
Here is a more challenging exercise. Suppose I tell you that, in a town,
there is a (male) barber that shaves all and only the men who do not
shave themselves. You can show that this is a contradiction, arguing
informally, as follows:
#+BEGIN_QUOTE
By the assumption, the barber shaves himself if and only if he does
not shave himself. Call this statement (*).

Suppose the barber shaves himself. By (*), this implies that he does
not shave himself, a contradiction. So, the barber does not shave
himself.

But using (*) again, this implies that the barber shaves himself,
which contradicts the fact we just showed, namely, that the barber
does not shave himself. 
#+END_QUOTE
Try to turn this into a formal argument in natural deduction.

Let us return to the example of the natural numbers, to see how
deductive notions play out there. Suppose we have defined $\fn{even}$
and $\fn{odd}$ in such a way that we can prove:
- $\fa n (\neg \even(n) \to \odd(n))$
- $\fa n (\odd(n) \to \neg \even(n))$
Then we can go on to derive $\fa n (\even(n) \vee \odd(n))$ as
follows:
\begin{prooftree}
\AXM{}
\UIM{\even(n) \vee \neg \even(n)}
\AXM{}
\RLM{1}
\UIM{\even(n)}
\UIM{\even(n) \vee \odd(n)}
\AXM{}
\UIM{\fa n \neg \even(n) \to \odd(n)}
\UIM{\neg \even (n) \to \odd(n)}
\AXM{}
\RLM{1}
\UIM{\neg \even(n)}
\BIM{\odd(n)}
\UIM{\even(n) \vee \odd(n)}
\RLM{1}
\TIM{\even(n) \vee \odd(n)}
\UIM{\fa n (\even (n) \vee \odd(n)}
\end{prooftree}
We can also prove and $\fa n \neg (\even(n) \wedge \odd(n))$:
\begin{prooftree}
\AXM{}
\UIM{\odd(n) \to \neg \even(n)}
\AXM{}
\RLM{H}
\UIM{\even(n) \wedge \odd(n)}
\UIM{\odd(n)}
\BIM{\neg \even(n)}
\AXM{}
\RLM{H}
\UIM{\even(n) \wedge \odd(n)}
\UIM{\even(n)}
\BIM{\bot}
\RLM{H}
\UIM{\neg (\even(n) \wedge \odd(n))}
\UIM{\fa n \neg (\even(n) \wedge \odd(n))}
\end{prooftree}
As we move from modeling basic rules of inference to modeling actual
mathematical proofs, we will tend to shift focus from natural
deduction to formal proofs in Lean. Natural deduction has its uses: as
a model of logical reasoning, it provides us with a convenient means
to study metatheoretic properties such as soundness and
completeness. For working /within/ the system, however, proof
languages like Lean's tend to scale better, and produce more readable
proofs.

** The Existential Quantifier

The following example illustrates the elimination rule for the
existential quantifier:
\begin{prooftree}
\AXM{}
\RLM{2}
\UIM{\ex x (A(x) \wedge B(x))}
\AXM{}
\RLM{1}
\UIM{\fa x (A(x) \to \neg B(x))}
\UIM{A(x) \to \neg B(x)}
\AXM{}
\RLM{3}
\UIM{A(x) \wedge B(x)}
\UIM{A(x)}
\BIM{\neg B(x)}
\AXM{}
\RLM{3}
\UIM{A(x) \wedge B(x)}
\UIM{B(x)}
\BIM{\bot}
\RLM{3}
\BIM{\bot}
\RLM{2}
\UIM{\neg\ex x(A(x) \wedge B(x))}
\RLM{1}
\UIM{\fa x (A(x) \to \neg B(x)) \to \neg\ex x(A(x) \wedge B(x))}
\end{prooftree}
In this proof, the existential elimination rule (the line labeled $3$)
is used to cancel two hypotheses at the same time. Note that when this
rule is applied, the hypothesis $\fa x (A(x) \to \neg B(x))$ has not
yet been canceled. So we have to make sure that this formula doesn't
contain the variable $x$ freely. But this is o.k., since this
hypothesis contains $x$ only as a bound variable.

Another example is that if $x$ does not occur in $P$, then $\ex x P$
is equivalent to $P$:
\begin{prooftree}
\AXM{}
\RLM{1}
\UIM{\ex x P}
\AXM{}
\RLM{2}
\UIM{P}
\RLM{2}
\BIM{P}
\AXM{}
\RLM{1}
\UIM{P}
\UIM{\ex x P}
\RLM{1}
\BIM{\ex x P \liff P}
\end{prooftree}
This short but tricky, so let us go through it carefully. On the left,
we assume $\ex x P$ to conclude $P$. We assume $P$, and now we can
immediately cancel this assumption by existential elimination, since
$x$ does not occur in $P$, so it doesn't occur freely in any
assumption or in the conclusion. On the right we use existential
introduction to conclude $\ex x P$ from $P$.

** Equality 

Recall the natural deduction rules for equality:
\begin{center}
\AXM{}
\UIM{t = t}
\DP
\quad
\AXM{s = t}
\UIM{t = s}
\DP
\quad
\AXM{r = s}
\AXM{s = t}
\BIM{r = t}
\DP
\\
\ \\
\AXM{s = t}
\UIM{r(s) = r(t)}
\DP
\quad
\AXM{s = t}
\AXM{P(s)}
\BIM{P(t)}
\DP
\end{center}
Keep in mind that we have implicitly fixed some first-order language,
and $r$, $s$, and $t$ are any terms in that language. Recall also that
we have adopted the practice of using functional notation with
terms. For example, if we think of $r(x)$ as the term $(x + y) \times
(z + 0)$ in the language of arithmetic, then $r(0)$ is the term $(0 +
y) \times (z + 0)$ and $r(u + v)$ is $((u + v) + y) \times (z +
0)$. So one example of the first inference on the second line is this:
\begin{center}
\AXM{u + v = 0}
\UIM{((u + v) + y) \times (z + 0) = (0 + y) \times (z + 0)}
\DP
\end{center}
The second axiom on that line is similar, except now $P(x)$ stands for
any /formula/, as in the following inference:
\begin{center}
\AXM{u + v = 0}
\AXM{x + (u + v) < y}
\BIM{x + 0 < y}
\DP
\end{center}
Notice that we have written the reflexivity axiom, $t = t$, as a rule
with no premises. If you use it in a proof, it does not count as a
hypothesis; it is built into the logic.

In fact, we can think of the first inference on the second line as a
special case of the first. Consider, for example, the formula $((u +
v) + y) \times (z + 0) = (x + y) \times (z + 0)$. If we plug $u + v$
in for $x$, we get an instance of reflexivity. If we plug in $0$, we
get the conclusion of the first example above. The following is
therefore a derivation of the first inference, using only reflexivity
and the second substitution rule above:
\begin{center}
\AXM{u + v = 0}
\AXM{}
\UIM{((u + v) + y) \times (z + 0) = ((u + v) + y) \times (z + 0)}
\BIM{((u + v) + y) \times (z + 0) = (0 + y) \times (z + 0)}
\DP
\end{center}
Roughly speaking, we are replacing the second instance of $u + v$ in 
an instance of reflexivity with $0$ to get the conclusion we want.

Equality rules let us carry out calculations in symbolic logic. This
typically amounts to using the equality rules we have already
discussed, together with a list of general identities. For example,
the following identities hold for any real numbers $x$, $y$, and $z$:
- commutativity of addition: $x + y = y + x$
- associativity of addition: $(x + y) + z = x + (y + z)$
- additive identity: $x + 0 = 0 + x = x$
- additive inverse: $-x + x = x + -x = 0$
- multiplicative identity: $x \cdot 1 = 1 \cdot x = x$
- commutativity of multiplication: $x \cdot y = y \cdot x$
- associativity of multiplication: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$
- distributivity: $x \cdot (y + z) = x \cdot y + x \cdot z, \quad (x +
  y) \cdot z = x \cdot z + y \cdot z$
You should imagine that there are implicit universal quantifiers in
front of each statement, asserting that the statement holds for /any/
values of $x$, $y$, and $z$. Note that $x$, $y$, and $z$ can, in
particular, be integers or rational numbers as well. Calculations
involving real numbers, rational numbers, or integers generally
involve identities like this.

The strategy is to use the elimination rule for the universal
quantifier to instantiate general identities, use symmetry, if
necessary, to orient an equation in the right direction, and then
using the substitution rule for equality to change something in a
previous result. For example, here is a natural deduction proof of a
simple identity, $\fa {x, y, z} ((x + y) + z = (x + z) + y)$, using
only commutativity and associativity of addition. We have taken the
liberty of using a brief name to denote the relevant identities, and
combining multiple instances of the universal quantifier introduction
and elimination rules into a single step.
\begin{center}
\AXM{}
\UIM{\mathsf{assoc}}
\UIM{(x + z) + y = x + (z + y)}
\UIM{x + (z + y) = (x + z) + y}
\AXM{}
\UIM{\mathsf{comm}}
\UIM{y + z = z + y}
\AXM{}
\UIM{\mathsf{assoc}}
\UIM{(x + y) + z = x + (y + z)}
\BIM{(x + y) + z = x + (z + y)}
\BIM{(x + y) + z = (x + z) + y}
\UIM{\fa {x, y, z} ((x + y) + z = (x + z) + y)}
\DP
\end{center}
There is generally nothing interesting to be learned from carrying out
such calculations in natural deduction, but you should try one or two
examples to get the hang of it, and then take pleasure in knowing that
it is possible.

** Counterexamples and Relativized Quantifiers

Consider the statement:
#+BEGIN_QUOTE
Every prime number is odd.
#+END_QUOTE
In first-order logic, we could formulate this as $\fa p (\fn{prime}(p)
\to \fn{odd}(p))$. This statement is false, because there is a prime
number which is even, namely the number 2. This is called a
/counterexample/ to the statement.

More generally, given a formula $\fa x A(x)$, a counterexample is a
value $t$ such that $\neg A(t)$ holds. Such a counterexample shows
that the original formula is false, because we have the following
equivalence: $\neg\fa x A(x) \liff \ex x \neg A(x)$. So if we find a
value $t$ such that $\neg A(t)$ holds, then by the existential
introduction rule we can conclude that $\ex x \neg A(x)$, and then by
the above equivalence we have $\neg\fa x A(x)$. Here is a proof of the equivalence:
\begin{prooftree}
\AXM{}
\RLM{1}
\UIM{\neg\fa x A(x)}
\AXM{}
\RLM{4}
\UIM{\neg(\ex x \neg A(x))}
\AXM{}
\RLM{5}
\UIM{\neg A(x)}
\UIM{\ex x \neg A(x)}
\BIM{\bot}
\RLM{5}
\UIM{A(x)}
\UIM{\fa x A(x)}
\BIM{}
\RLM{4}
\UIM{\ex x \neg A(x)}
\AXM{}
\RLM{1}
\UIM{\ex x \neg A(x)}
\AXM{}
\RLM{3}
\UIM{\neg A(y)}
\AXM{}
\RLM{2}
\UIM{\fa x A(x)}
\UIM{A(y)}
\BIM{\bot}
\RLM{3}
\BIM{\bot}
\RLM{2}
\UIM{\neg\fa x A(x)}
\RLM{1}
\BIM{\neg\fa x A(x) \liff \ex x \neg A(x)}
\end{prooftree}
One remark about the proof: at the step marked by $4$ we /cannot/ use
the existential introduction rule, because at that point our only
assumption is $\neg\fa x A(x)$, and from that assumption we cannot
prove $\neg A(t)$ for a particular term $t$. So we use a proof by
contradiction there.

As an exercise, prove the "dual" equivalence yourself: $\neg\ex x A(x)
\liff \fa x \neg A(x)$. This can be done without using proof by
contradiction.

In Chapter [[file:04_First_Order_Logic.org::#First_Order_Logic][First Order Logic]] we saw examples of how to use
relativization to restrict the scope of a universal
quantifier. Suppose we want to say "every prime number is greater than
1". In first order logic this can be written as $\fa n (\fn{prime}(n)
\to n > 1)$. The reason is that the original statement is equivalent
to the statement "for every natural number, if it is prime, then it is
greater than 1". Similarly, suppose we want to say "there exists a
prime number greater than 100." This is equivalent to saying "there
exists a natural number which is prime and greater than 100," which
can be expressed as $\ex n(\fn{prime}(n) \wedge n > 100)$.

As an exercise you can prove the above results about negations of
quantifiers also for relativized quantifiers. Specifically, prove the
following statements:
- $\neg\ex x (A(x) \wedge B(x)) \liff \fa x ( A(x) \to \neg B(x))$;
- $\neg\fa x (A(x) \to B(x)) \liff \ex x ( A(x) \wedge \neg B(x))$

For reference, here is a list of valid sentences involving
quantifiers:
- $\fa x A \liff A$ if $x$ is not free in $A$
- $\ex x A \liff A$ if $x$ is not free in $A$
- $\fa x (A(x) \land B(x)) \liff \fa x A(x) \land \fa x B(x)$
- $\ex x (A(x) \land B) \liff \ex x A(x) \land B$ if $x$ is
  not free in $B$
- $\ex x (A(x) \lor B(x)) \liff \ex x A(x) \lor \ex x B(x)$
- $\fa x (A(x) \lor B) \liff \fa x A(x) \lor B$ if $x$ is not
  free in $B$
- $\fa x (A(x) \to B) \liff (\ex x A(x) \to B)$ if
  $x$ is not free in $B$
- $\ex x (A(x) \to B) \liff (\fa x A(x) \to
  B)$ if $x$ is not free in $B$
- $\fa x (A \to B(x)) \liff (A \to \fa x B(x))$ if
  $x$ is not free in $A$
- $\ex x (A(x) \to B) \liff (A(x) \to \ex x B)$
  if $x$ is not free in $B$
- $\ex x A(x) \liff \neg \fa x \neg A(x)$
- $\fa x A(x) \liff \neg \ex x \neg A(x)$
- $\neg \ex x A(x) \liff \fa x \neg A(x)$
- $\neg \fa x A(x) \liff \ex x \neg A(x)$
All of these can be derived in natural deduction. The last two allow
us to push negations inwards, so we can continue to put first-order
formulas in negation normal form. Other rules allow us to bring
quantifiers to the front of any formula, though, in general, there
will be multiple ways of doing this. For example, the formula
\begin{equation*}
\fa x A(x) \to \ex y \fa z B(y, z)
\end{equation*}
is equivalent to both
\begin{equation*}
\ex {x, y} \fa z (A(x) \to B(y, z))
\end{equation*}
and
\begin{equation*}
\ex y \fa z \ex x (A(x) \to B(y, z)).
\end{equation*}
A formula with all the quantifiers in front is said to be in /prenex/
form.


** Exercises

1.  Give a natural deduction proof of $\fa x B(x)$ from hypotheses
    $\fa x (A(x) \vee B(x))$ and $\fa y \neg A(y)$.

2.  From hypotheses $\fa x (\fn{even}(x) \vee \fn{odd}(x))$ and $\fa x
    (\fn{odd}(x) \to \fn{even}(s(x)))$ give a natural deduction proof
    $\fa x (\fn{even}(x) \vee \fn{even}(s(x)))$. (It might help to
    think of $s(x)$ as the function defined by $s(x) = x + 1$.)

3.  Give a natural deduction proof of $\ex x A(x) \vee \ex x B(x) \to
    \ex x (A(x) \vee B(x))$.

4.  Give a natural deduction proof of $\ex x (A(x) \vee B(x)) \to \ex
    x A(x) \vee \ex x B(x)$.

5.  Give a natural deduction proof of $\ex x (A(x) \wedge C(x))$ from
    the assumptions $\ex x (A(x) \wedge B(x))$ and $\fa x (A(x) \wedge
    B(x) \to C(x))$.

6.  Prove some of the other equivalences in the last section.

7.  Consider some of the various ways of expressing ``nobody trusts a
    politician'' in first-order logic:

    - $\fa x (\fn{politician}(x) \to \fa y (\neg \fn{trusts}(y,x)))$
    - $\fa {x,y} (\fn{politician}(x) \to \neg \fn{trusts}(y,x))$
    - $\neg \ex{x,y} (\fn{politician}(x) \wedge \fn{trusts}(y,x))$
    - $\fa {x, y} (\fn{trusts}(y,x) \to \neg \fn{politician}(x))$

    They are all logically equivalent. Show this for (b) and (d), by
    giving natural deduction proofs of each from the other. (As a
    shortcut, in the $\forall$ introduction and elimination rules, you
    can introduce / eliminate both variables in one step.)

8.  Formalize the following statements, and give a natural deduction
    proof in which the first three statements appear as (uncancelled)
    hypotheses, and the last line is the conclusion:

    - Every young and healthy person likes baseball.
    - Every active person is healthy.
    - Someone is young and active.
    - Therefore, someone likes baseball.

    Use $Y(x)$ for ``is young,'' $H(x)$ for ``is healthy,'' $A(x)$ for
    ``is active,'' and $B(x)$ for ``likes baseball.''

9.  Give a natural deduction proof of $\fa {x, y, z} (x = z \to (y = z
    \to x = y))$ using the equality rules in Section 5.1 in the online
    notes.

10. Give a natural deduction proof of $\fa {x, y} (x = y \to y = x)$
    using only these two hypotheses (and none of the new equality
    rules):

   - $\fa x (x = x)$
   - $\fa {u, v, w} (u = w \to (v = w \to u = v))$

   (Hint: Choose instantiations of $u$, $v$, and $w$ carefully. You
   can instantiate all the universal quantifiers in one step, as on
   the last homework assignment.)

11. Give a natural deduction proof of $\neg \ex x (A(x) \wedge B(x))
    \liff \fa x (A(x) \to \neg B(x))$

12. Give a natural deduction proof of $\neg \fa x (A(x) \to B(x))
    \liff \ex x (A(x) \wedge \neg B(x))$

13. Remember that both the following express $\exists!x \; A(x)$, that
    is, the statment that there is a unique $x$ satisfying $A(x)$:

    - $\ex x (A(x) \wedge \fa y (A(y) \to y = x))$
    - $\ex x A(x) \wedge \fa y \fa {y'} (A(y) \wedge A(y') \to y = y')$ 

    Do the following:

    - Give a natural deduction proof of the second, assuming the first
      as a hypothesis.
    - Give a natural deduction proof of the first, asssuming the
      second as a hypothesis.

    (Warning: these are long.)

