#+Title: Logic and Proof
#+Author: [[http://www.andrew.cmu.edu/user/avigad][Jeremy Avigad]], [[http://www.andrew.cmu.edu/user/rlewis1/][Robert Y. Lewis]],  [[http://www.contrib.andrew.cmu.edu/~fpv/][Floris van Doorn]]

* Elementary Number Theory
:PROPERTIES:
  :CUSTOM_ID: Elementary_Number_Theory
:END:

** The Natural Numbers

we have come to a turning point in this textbook. We will henceforth,
for the most part, abandon natural deduction, and begin to focus on
ordinary mathematical proofs. We will continue to think about how
informal mathematics can be represented in symbolic terms, and how the
rules of natural deduction play out in the informal setting. But the
focus will be on writing ordinary mathematical arguments, not
designing proof trees. Lean will continue to serve as a bridge between
the informal and formal realms.

As a first foray into the real of mathematical proof, we will start
with some ordinary reasoning about the natural numbers. Remember that
the set of natural numbers is the set
\[
\NN = \{ 0, 1, 2, 3, \ldots \},
\]
in contrast to the integers,
\[
\ZZ = \{ \ldots, -2, -1, 0, 1, 2, \ldots \},
\]
which include negative numbers as well.

We will first talk about the natural numbers. On the natural numbers, we have addition and
multiplication. These operations satisfy the equalities and properties below. We will not prove
these properties for now, but instead assume them as the basic properties of addition and
multiplication. They can be used without further justification.
\begin{align*}
m + n &= n + m &&\text{(commutativity of addition)}\\
m + (n + k) &= (m + n) + k &&\text{(associativity of addition)}\\
n + 0 &= n &&\text{($0$ is a neutral element for addition)}\\
n \cdot m &= m \cdot n &&\text{(commutativity of multiplication)}\\
m \cdot (n \cdot k) &= (m \cdot n) \cdot k &&\text{(associativity of multiplication)}\\
n \cdot 1 &= n &&\text{($1$ is an neutral element for multiplication)}\\
n \cdot (m + k) &= n \cdot m + n \cdot k &&\text{(distributivity)}\\
n \cdot 0 &= 0 &&\text{($0$ is an absorbing element for multiplication)}
\end{align*}
We also have the following properties:
- $n + 1 \neq 0$;
- if $n + k = m + k$ then $n = m$;
- if $n \cdot k = m \cdot k$ and $k \neq 0$ then $n = m$.

We will often write simply $nm$ instead of $n \cdot m$ for multiplication.

We also have an ordering "less than", $<$, on the natural numbers. This /strict inequality/
satisfies the following basic properties. Again, these properties can be used without justification.
- $n < n$ is never true (/irreflexivity/);
- if $n < m$ and $m < k$ then $n < k$ (/transitivity/);
- for all $n$ and $m$, either $n < m$, $n = m$ or $m < n$ is true (/trichotomy/);
- if $n < m$ then $n + k < m + k$;
- if $k > 0$ and $n < m$ then $nk < mk$;
- if $m > n$ then $m = n + 1$ or $m > n + 1$;
- for all $n$, $n = 0$ or $n > 0$.

The relation $x \le y$, read "$x$ is less than or equal to $y$," is defined to mean just that, that
is, the $x$ is less than $y$ or $x$ is equal to $y$.

Now from the properties of $<$ we can prove similar properties for $\le$. Note that these properties
are /not/ basic properties we assume, but are instead properties we can derive from the properties
of $<$ and the definition of $\le$.
- $n \le n$ (/reflexivity/);
- if $n \le m$ and $m \le k$ then $n \le k$ (/transitivity/);
- if $n \le m$ and $m \le n$ then $n = m$ (/antisymmetry/);
- for all $n$ and $m$, either $n \le m$ or $m \le n$ is true (/totality/);
- if $n \le m$ then $n + k \le m + k$;
- if $n \le m$ then $nk \le mk$;
- if $m \ge n$ then $m = n$ or $m \ge n + 1$;
- $0 \le n$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proof*. We will prove some of these properties listed for $\le$.

The first property is straightforward. Since $n \le n$ is defined as "$n = n$ or $n < n$," it is
true, since the equality holds.

For the second property assume that $n \le m$ and $m \le k$. We have to show that $n \le k$. By
definition of $\le$ we know from our first assumption that either $n = m$ or $n < m$. We now apply
case analysis.
- Suppose first that $n = m$. Since we know that $m \le k$, we can substitute $n$ for $m$ in that
  expression to obtain $n \le k$, which is what we wanted to prove.
- Now suppose that $n < m$. Then we know from our second assumption that either $m = k$ or $m <
  k$. We perform a second case distinction.
  - If $m = k$ then we can substitute $k$ for $m$ in the inequality $n < m$ to obtain $n < k$. Hence
    we conclude that $n \le k$, as desired.
  - In the other case, if $m < k$, then we use the transitivity of $<$ to conclude from $n < m$ and
    $m < k$ that $n < k$. Hence we know that $n \le k$.
In all cases we've shown that $n \le k$, so we've finished the proof.

As a last example, we show that if $n \le m$ then $nk \le mk$. By assumption, we have either $n = m$
or $n < m$. If $n = m$, then we know by multiplying both sides with $k$ that $nk = mk$, hence $nk
\le mk$. On the other hand, if $n < m$, then apply case analysis on $k = 0$ or $k > 0$, which is one
of the properties for the strict inequality. If $k = 0$, then $nk = n \cdot 0 = 0 = m \cdot 0 = mk$,
hence $nk \le mk$. If $k > 0$ we can conclude that $nk < mk$ by one of the properties for the strict
inequality, hence that $nk \le mk$.  Since in all cases we've proven that $nk \le mk$, we have
finished the proof of this property.

The rest of the proofs are left as an exercise to the reader.

#+HTML: <hr>
#+LATEX: \horizontalrule

We can prove some more properties about $<$ and $\le$. These are not basic properties we assume, but
properties we can prove from the basic properties for $<$, which you are asked to do in the
exercises below.
- $n < m$ and $m < n$ cannot both hold (/asymmetry/);
- $n + 1 > n$;
- if $n < m$ and $m \le k$ then $n < k$;
- if $n \le m$ and $m < k$ then $n < k$;
- if $m > n$ then $m \ge n + 1$;
- if $m \ge n$ then $m + 1 > n$;
- if $n + k < m + k$ then $n < m$;
- if $nk < mk$ then $k > 0$ and $n < m$.

We will now prove some statements from the given properties above.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Example*. If $n$ and $m$ are natural numbers such that $n + m = 0$, then $n = m = 0$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proof*. We first prove that $m = 0$. We know that $m = 0$ or $m > 0$. Suppose that $m > 0$ Then
$n + m > n + 0 = n$. Since $n \ge 0$, we conclude that $n + m > 0$, which is in contradiction with
$n + m = 0$. Since $m > 0$ leads to a contradiction, the other option that $m = 0$ must hold.

Now we can easily conclude that $n = 0$ using the following chain of equalities $n = n + 0 = n + m =
0$. Hence $n = m = 0$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Example*. If $n$ is a natural number such that $n < 3$, then $n = 0$, $n = 1$ or $n = 2$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proof*. In this proof we repeatedly use the property that if $m > n$ then $m = n + 1$ or $m > n +
1$. Since $2 + 1 = 3 > n$, we conclude that either $2 + 1 = n + 1$ or $2 + 1 > n + 1$. In the first
case we conclude $n = 2$, and we are done. In the second case we conclude $2 > n$. Now we conclude
that either $2 = n + 1$, or $2 > n + 1$. In the first case, we conlude $n = 1$, and we are done. In
the second case, we conclude $1 > n$. One last time we use the property mentioned above, to conclude
that either $1 = n + 1$ or $1 > n + 1$. In the first case, we conclude $n = 0$, and we are once
again done. In the second case, we conclude that $0 > n$. This leads to a contradiction, since now
$0 > n \ge 0$, hence $0 > 0$, which contradicts the irreflexivity of $>$.

#+HTML: <hr>
#+LATEX: \horizontalrule

For the integers the properties are mostly the same as mentioned above. Some of the properties do
not hold, though. The two basic properties which do not hold anymore are that $n + 1 \neq 0$ (which
is false for $n = -1$) and the property that either $n = 0$ or $n > 0$ (which is false for all
negative numbers). Look for yourself through the derived properties and examples to see which of
those properties fail on the integers.

On the integers, we can negate any number $n$ to get $-n$, satisfying $n + (-n) = 0$. We write $n +
(-m)$ as the subtraction $n - m$.

On the natural numbers, subtraction doesn't always return a natural number. If $n$ and $m$
are natural numbers then $n - m$ is only a natural number if $n \ge m$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Exercises*. Prove the following things in an informal style, similar to the proofs given above.
- We derived some properties for $\le$ from the properties of $<$ and the definition of
  $\le$. Derive the remaining properties for $\le$.
- Prove the list of properties for $<$ and $\le$ from the basic properties of $<$.
- Prove that if $n < 5$ then $n$ is either of the values $0, 1, 2, 3, 4$.
- Prove that if $nm = 1$ then $n = m = 1$.
# Tricky. Proof sketch: n ≠ 0, hence n > 0. Similarly m > 0. Hence m = 1 or m > 1.
# Assume m > 1, then nm > n. Now both n = 1 and n > 1 imply that nm > 1, contradiction.
- Prove the following properties for negation and subtraction on the integers. You can only use the
  definitions of negation and subtraction given above.
  - if $n + m = 0$ then $m = -n$;
  - $-0 = 0$;
  - if $-n = -m$ then $n = m$;
  - $m + (n - m) = n$;
  - $-(n + m) = -n - m$;
  - if $m < n$ then $n - m > 0$;
  - if $m < n$ then $-m > -n$;
  - $n \cdot (-m) = -nm$;
  - $n(m - k) = nm - nk$;
  - if $n < m$ then $n - k < m - k$.

# Do we want more properties here?

#+HTML: <hr>
#+LATEX: \horizontalrule

We will see in a later chapter that a key property of the natural
numbers is that it supports /proof by induction/ and /definition by
recursion/. Moreover, with these components, we can actually define
$+$, $\times$, and $<$ in a suitable axiomatic foundation, and prove
that they have the relevant properties. For now, let's keep in mind
that the foundations of a building are typically underground. Right
now, we will enter mathematics at the ground level and proceed from
there. In the proofs below, we will use the facts above without naming
them or justifying them; they will be assumed to be part of the common
background. On the other hand, for example, we will rigorously define
the notion "$m$ divides $n$," written $m \mid n$, and prove that it
has the expected properties.

A key property of the natural numbers that we will use here is the
quotient-remainder theorem:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* Let $n$ and $m$ be natural numbers with $m > 0$. Then there
are natural numbers $q$ and $r$ satisfying $n = m q + r$ and $r < m$.

#+HTML: <hr>
#+LATEX: \horizontalrule

Later we will see how to prove this from the definitions of
multiplication and addition; for now, we will simply take it for
granted.

Intuitively, $q$ is the integer /quotient/ when you divide $n$ by $m$, and
$r$ is the /remainder/. Remember that using the word "the" presupposes
that there are unique values meeting that description. That is, in
fact, the case:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proposition*. If $n$ and $m$ are as above, $n = m q + r$ and $n =
m q' + r'$ with both $r$ and $r'$ less than $n$, then $q = q'$ and $r
= r'$.

*Proof*. By assumption, we have $mq + r = m q' + r'$. It suffices to
show that $q = q'$, because then $m q = m q'$, and hence $r = r'$.

Suppose $q \ne q'$. Then either $q < q'$ or $q' < q$. Suppose without
loss of generality that $q < q'$. (The other case is symmetric.) Then
$m q < m q'$, so we can subtract $mq$ from both sides of the equality
$mq + r = m q' + r'$ to obtain
\[
r = m q' + r - m q = m (q - q') + r'.
\]
But since $q' < q$, we have $q - q' \ge 1$, which means
\[
m (q - q') + r' \ge m + r' \ge m,
\]
which contradicts the fact that $r < m$.

#+HTML: <hr>
#+LATEX: \horizontalrule

Since we have proven that the quotient and remainder are unique when you divide $n$ by $m$, we can
define functions which compute these numbers. We write $\lfloor n / m \rfloor$ for the quotient and
$n \mod m$ for the remainder.

** Divisibility

We can define divisibility on the natural numbers as follows.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Definition*. Given two natural numbers $m$ and $n$. We say that $m$
 /is a divisor of/ $n$, written $m \mid n$, if there exists some $k$
 such that $m \cdot k = n$. We also say that $n$ /is divisible by/ $m$
 or that $m$ /divides/ $n$.

#+HTML: <hr>
#+LATEX: \horizontalrule

We can now prove the following:

#+HTML: <hr>
#+LATEX: \horizontalrule
# Note: reflexive, antisymmetric and transitive are already mentioned above.
*Theorem.* The relation $\mid$ is reflexive, antisymmetric and transitive. That is
- $n \mid n$ (/reflexivity/);
- if $n \mid m$ and $m \mid n$ then $n = m$ (/antisymmetry/);
- if $m \mid n$ and $n \mid r$ then $m \mid r$ (/transitivity/).

*Proof.* Reflexivity is immediate, because $n \cdot 1 = n$, hence
$n\mid n$.

For antisymmetry, suppose that $n$ and $m$ are natural numbers such that $n\mid m$ and $m \mid
n$. Then there exist $k$ and $\ell$ such that $n\cdot k = m$ and $m \cdot \ell = n$. We distinguish
two cases. If $n = 0$, then we have $m = n\cdot k = 0 = n$, so we are done. If $n > 0$, then we use
the the equations to get $n \cdot k \cdot \ell = m \cdot \ell = n$, and we can cancel $n$ on both
sides to get $k \cdot \ell = 1$. We conclude that $k = \ell = 1$, hence we get $n = n \cdot k = m$,
so $\mid$ is antisymmetric.

Finally, to prove transitivity, suppose $m \mid n$ and $n \mid r$. Then there are $k,\ell$ such that
$m \cdot k = n$ and $n \cdot \ell = r$. Now we compute
\begin{align*}
m \cdot (k \cdot \ell) &= (m \cdot k) \cdot \ell \\
& = n \cdot \ell  \\
& = r.
\end{align*}
#+HTML: <hr>
#+LATEX: \horizontalrule

Let us close with some examples of elementary theorems of number
theory. (These are all exercises in Chapter 1 of /An Introduction to
the Theory of Numbers/ by Niven and Zuckerman.)

# define even, odd, prove odd => 2 k + 1, prove that in a sequence of k consecutive numbers, one of
# them is divisible by k.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* The product of any three consecutive integers is divisible
by 6.

*Proof.* Denote the three integers by $n$, $n + 1$, and $n + 2$. Then
either $n$ or $n + 1$ is divisible by 2, and either $n$, $n + 1$, or
$n + 2$ is divisible by 3. So, their product is divisible by 6.

*Theorem*. For every $n$, $n^3 - n$ is divisible by 6.

*Proof.* We have $n^3 - n = (n - 1) n (n + 1)$, which is a product of
 three consecutive integers.

#+HTML: <hr>
#+LATEX: \horizontalrule

As exercises, try writing proving the following, informally:
- For any integer $n$, $n^2$ leaves a remainder of 0 or 1
  when you divide it by 4. Hence $n^2 + 2$ is never divisible by 4.
- If $n$ is odd, $n^2 - 1$ is divisible by 8.
- If $m$ and $n$ are odd, then $m^2 + n^2$ is even but not divisible
  by 4.
- Say that two integers "have the same parity" if they are both even
  or both odd. Prove that if $m$ and $n$ are any two integers, then
  $m + n$ and $m - n$ have the same parity.

Notice that the proofs above do not look anything like proofs in
symbolic logic. For one thing, ordinary proofs tend to favor words
over symbols. Of course, mathematics uses symbols all the time, but
not in place of words like "and" and "not"; you will rarely, if ever,
see the symbols $\wedge$ and $\neg$ in a mathematics textbook, unless
it is a textbook specifically about logic.

Similarly, the structure of an informal proof is conveyed with
ordinary paragraphs and punctuation. Don't rely on pictorial diagrams,
line breaks, and indentation to convey the structure of a
proof. Rather, you should rely on literary devices like signposting
and foreshadowing. It is often helpful to present an outline of a
proof or the key ideas before delving into the details, and the
introductory sentence of a paragraph can help guide a reader's
expectations, just as it does in an expository essay.

Perhaps the biggest difference between informal proofs and formal
proofs is the level of detail. Informal proofs will often skip over
details that are taken to be "straightforward" or "obvious," devoting
more effort to spelling out inferences that are novel of unexpected.

Writing a good proof is like writing a good essay. To convince your
readers that the conclusion is correct, you have to get them to
understand the argument, without overwhelming them with unnecessary
details. It helps to have a specific audience in mind. Try speaking
the argument aloud to friends, roommates, and family members; if their
eyes glaze over, it is unreasonable to expect anonymous readers to do
better.

Perhaps the best way to learn to write good proofs is to /read/ good
proofs, and pay attention to the style of writing. Pick an example of
a textbook that you find especially clear and engaging, and think
about what makes it so.

Natural deduction and formal verification can help you understand the
components that make a proof /correct/, but you will have to develop
an intuitive feel for what makes a proof easy and enjoyable to read.

** Modular Arithmetic

# add chapter reference
In the discussion of equivalence relations in Chapter ?? we considered
the example of the relation of modular equivalence on the
integers. This is sometimes thought of as "clock arithmetic." Suppose
you have a 12-hour clock without a minute hand, so it only has an hour
hand which can point to the hours 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11 and then it wraps to 12 again. We can do arithmetic with this
clock.
- If the hand currently points to 10, then 5 hours later it will point to 3.
- If the hand points to 7, then 23 hours before that, it pointed to 8.
- If the hand points to 9, and we work for a 8 hours, then when we are
  done the hand will point to 5. If we worked twice as long, starting
  at 9, the hand will point to 1.

We want to write these statements using mathematical notation, so that
we can reason about them more easily. We cannot write $10 + 5 = 3$ for
the first expression, because that would be false, so instead we use
the notation $10 + 5 \equiv 3 \pmod{12}$. The notation $\pmod{12}$
indicates that we forget about multiples of 12, and we use the
"congruence" symbol with three horizontal lines to remind us that
these values are not exactly equal, but only equal up to multiples
of 12. The other two lines can be formulated as $7 - 23 \equiv 8
\pmod{12}$ and $9 + 2 \cdot 8 \equiv 1 \pmod{12}$.

Here are some more examples:
- $6 + 7 \equiv 1 \pmod{12}$
- $6 \cdot 7 \equiv 42 \equiv 6 \pmod{12}$
- $7 \cdot 5 \equiv 35 \equiv -1 \pmod{12}$
The last example shows that we can use negative numbers as well.

We now give a precise definition.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Definition*. For integers $a$, $b$ and $n$ we say that $a$ and $b$
are /congruent modulo/ $n$ if $n \mid a - b$. This is written $a
\equiv b \pmod{n}$. The number $n$ is called the /modulus/.

#+HTML: <hr>
#+LATEX: \horizontalrule

Typically we only use this definition when the modulus $n$ is
positive.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem*. Congruence modulo $n$ is an equivalence relation.

*Proof*. We have to show that congruence modulo $n$ is reflexive,
symmetric and transitive.

It is reflexive, because $a - a = 0$, so $n \mid a - a$, and hence
$a\equiv a \pmod{n}$.

To show that it is symmetric, suppose that $a \equiv b \pmod{n}$. Then
by definition, $n \mid a - b$. So $n \mid (-1) \cdot (a - b)$, which
means that $n \mid b - a$. This means by definition that $b \equiv a
\pmod{n}$.

To show that it is transitive, suppose that $a \equiv b \pmod{n}$ and
$b \equiv c \pmod{n}$. Then we have $n \mid a - b$ and $n \mid b -
c$. Hence by the previous proposition we have $n \mid (a - b) + (b -
c)$ which means that $n \mid a - c$. So $a \equiv c \pmod{n}$.

#+HTML: <hr>
#+LATEX: \horizontalrule

This theorem justifies the "chaining" notation we used above when we
wrote $7 \cdot 5 \equiv 35 \equiv -1 \pmod{12}$. Since congruence
modulo 12 is transitive, we can now actually conclude that $7\cdot
5\equiv -1 \pmod{12}$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem*. Suppose that $a\equiv b \pmod{n}$ and $c\equiv
d\pmod{n}$. Then $a+c\equiv b+d \pmod{n}$ and $a\cdot c\equiv b\cdot
d\pmod{n}$.

Moreover, if $a\equiv b \pmod{n}$ then $a^k\equiv b^k \pmod{n}$ for
all natural numbers $k$.

*Proof*. We know that $n \mid a - b$ and $n \mid c - d$. For the first
statement, we can calculate that $(a + c) - (b + d) = (a - b) + (c -
d)$, so we can conclude that $n \mid (a + c) - (b + d)$ hence that
$a+c\equiv b+d\pmod{n}$.

For the second statement, we want to show that $n \mid a\cdot c -
b\cdot d$. We can factor $a\cdot c - b\cdot d = (a - b)\cdot c +
b\cdot(c-d)$. Now $n$ divides both summands on the right, hence $n$
divides $a\cdot c - b\cdot d$, which means that $a\cdot c\equiv b\cdot
d\pmod{n}$.

The last statement follows by repeatedly applying the second
statement:
\begin{equation*}
a^k = \underbrace{a\cdot a \cdot \cdots \cdot a}_{\text{$k$ times}} \equiv
\underbrace{b\cdot b \cdot \cdots \cdot b}_{\text{$k$ times}} = b^k \pmod{n}
\end{equation*}

#+HTML: <hr>
#+LATEX: \horizontalrule

This theorem is useful for carrying out computations modulo $n$. Here
are some examples.
- Suppose we want to compute $77 \cdot 123$ modulo 12. We know that
  $77 \equiv 5 \pmod{12}$ and $123 \equiv 3 \pmod{12}$, so $77 \cdot
  123 \equiv 5 \cdot 3 \equiv 15 \equiv 3 \pmod{12}$
- Suppose we want to compute $99 \cdot 998$ modulo 10. We know that
  $99 \equiv -1\pmod{10}$ and $998 \equiv -2 \pmod{10}$, hence $99
  \cdot 998 \equiv (-1) \cdot (-2) \equiv 2 \pmod{10}$.
- Suppose we want to know the last digit of $101^{101}$. Notice that
  the last digit of a number $n$ is congruent to $n$ modulo 10, so we
  can just compute $101^{101} \equiv 1^{101} \equiv 1 \pmod{10}$. So
  the last digit of $101^{101}$ is 1.
- You are not allowed to compute in exponents with modular
  arithmetic. For example $8 \equiv 3 \pmod{5}$, but $2^8 \not\equiv
  2^3 \pmod{5}$. To see this: $2^8 = 256 \equiv 1 \pmod{5}$, but $2^3
  = 8 \equiv 3 \pmod{5}$.

Recall the quotient-remainder theorem:
if $n > 0$, then any integer $a$ can be expressed as $a = n q + r$,
where $0 \le r < n$. In the language of modular arithmetic this means
that $a \equiv r \pmod{n}$. So if $n > 0$, then every integer is
congruent to a number between 0 and $n-1$ (inclusive). So there "are
only $n$ different numbers" when working modulo $n$. This can be used
to prove many statements about the natural numbers.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proposition*. For every integer $k$, $k^2+1$ is not divisible by 3.

*Proof*. Translating this problem to modular arithmetic, we have to
show that $k^2+1 \not\equiv 0 \pmod{3}$ or in other words that
$k^2\not\equiv 2 \pmod{3}$ for all $k$. By the quotient-remainder
theorem, we know that $k$ is either congruent to 0, 1 or 2,
modulo 3. In the first case, $k^2\equiv 0^2\equiv 0\pmod{3}$. In the
second case, $k^{2}\equiv 1^2 \equiv 1 \pmod{3}$, and in the last case
we have $k^{2}\equiv2^2\equiv4\equiv1\pmod{3}$. In all of those cases,
$k^2\not\equiv2\pmod{3}$. So $k^2+1$ is never divisible by 3.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proposition*. For all integers $a$ and $b$, $a^2+b^2-3$ is not
divisible by 4.

*Proof*. We first compute the squares modulo 4. We compute
\begin{align*}
0^2&\equiv 0\pmod{4}\\
1^2&\equiv 1\pmod{4}\\
2^2&\equiv 0\pmod{4}\\
3^2&\equiv 1\pmod{4}
\end{align*}
Since every number is congruent to 0, 1, 2 or 3 modulo 4, we know that
every square is congruent to 0 or 1 modulo 4. This means that there
are only four possibilities for $a^2+b^2\pmod{4}$. It can be congruent
to $0+0$, $1+0$, $0+1$ or $0+0$. In all those cases,
$a^2+b^2\not\equiv 3\pmod{4}$ Hence $4\nmid a^2+b^2-3$, proving the
proposition.

#+HTML: <hr>
#+LATEX: \horizontalrule

Exercises:
- Show that for every integer $n$ the number $n^4$ is congruent to 0
  or 1 modulo 5. Hint: to simplify the computation, use that
  $4^4\equiv(-1)^4\pmod{5}$.
- Prove that the equation $n^4+m^4=k^4+3$ cannot hold for integers $n,
  m, k$. Hint: what are the possible values for the left hand side
  modulo 5? And for the right hand side?


** Proofs with Calculations

Calculation is a central to mathematics, and mathematical proofs often
involve carrying out calculations. Indeed, a calculation can be viewed
as a proof in and of itself that two expressions describe the same
entity.

In high school algebra, students are often asked to prove identities
like the following:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proposition.* $\frac{n(n+1)}{2} + (n + 1) = \frac{(n+1)(n+2)}{2}$,
for every natural number $n$.

#+HTML: <hr>
#+LATEX: \horizontalrule

In some places, students are asked to write proofs like this:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proof.*
\begin{align*}
 \frac{n(n+1)}{2} + (n + 1) & =? \frac{(n+1)(n+2)}{2} \\
 \frac{n^2+n}{2} + \frac{2n + 2}{2} & =? \frac{n^2 + 3n + 2}{2} \\
 \frac{n^2+n + 2n + 1}{2} & =? \frac{n^2 + 3n + 2}{2} \\
 \frac{n^2+3n + 1}{2} & = \frac{n^2 + 3n + 2}{2} \\
\end{align*}

#+HTML: <hr>
#+LATEX: \horizontalrule

Mathematicians generally cringe when they see this. /Don't do it!/ It
looks like an instance of forward reasoning, where we start with a
complex identity and end up proving $x = x$. Of course, what is really
meant is that each line follows from the next. There is a way of
expressing this, with the phrase "it suffices to show." The following
presentation comes closer to mathematical vernacular:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proof.* We want to show
\begin{equation*}
\frac{n(n+1)}{2} + (n + 1) = \frac{(n+1)(n+2)}{2}.
\end{equation*}
To do that, it suffices to show
\begin{equation*}
 \frac{n^2+n}{2} + \frac{2n + 2}{2} = \frac{n^2 + 3n + 2}{2}.
\end{equation*}
For that, it suffices to show
\begin{equation*}
 \frac{n^2+n + 2n + 1}{2} = \frac{n^2 + 3n + 2}{2}.
\end{equation*}
But this last equation is clearly true.

#+HTML: <hr>
#+LATEX: \horizontalrule

The narrative doesn't flow well, however. Sometimes there are good
reasons to work backwards in a proof, but in this case it is easy to
present the proof in a more forward-directed manner. Here is one
example:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proof.* Calculating on the left-hand side, we have
\begin{align*}
 \frac{n(n+1)}{2} + (n + 1) & = \frac{n^2+n}{2} + \frac{2n + 2}{2} \\
   & = \frac{n^2+n + 2n + 1}{2} \\
   & = \frac{n^2 + 3n + 1}{2}.
\end{align*}
On the right-hand side, we also have
\begin{equation}
 \frac{(n+1)(n+2)}{2} = \frac{n^2 + 3n + 1}{2}.
\end{equation}
So $\frac{n(n+1)}{2} + (n + 1) = \frac{n^2 + 3n + 1}{2}$, as required.

#+HTML: <hr>
#+LATEX: \horizontalrule

Mathematicians often use the abbreviations "LHS" and "RHS" for
"left-hand side" and "right-hand side," respectively, in situations
like this.  In fact, here we can easily write the proof as a single
forward-directed calculation:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proof.*
\begin{align*}
 \frac{n(n+1)}{2} + (n + 1) & = \frac{n^2+n}{2} + \frac{2n + 2}{2} \\
   & = \frac{n^2+n + 2n + 1}{2} \\
   & = \frac{n^2 + 3n + 1}{2} \\
   & = \frac{(n+1)(n+2)}{2}.
\end{align*}

#+HTML: <hr>
#+LATEX: \horizontalrule

Such a proof is clear, compact, and easy to read. The main challenge
to the reader is to figure out what justifies each subsequent
step. Mathematicians sometimes annotate such a calculation with
additional information, or add a few words of explanation in the text
before and/or after. But the ideal situation is to carry out the
calculation is small enough steps so that each step is
straightforward, and needs to no explanation. (And, once again, what
counts as "straightforward" will vary depending on who is reading the
proof.)

Let us consider another example. You may recall that if $n$ and $k$
are natural numbers and $k \leq n$, the notation $\binom{n}{k}$
denotes the number of ways of choosing $k$ objects out of $n$, without
repetitions, where the order does not matter. For example, if you have
ten shirts in your drawer, and want to choose three to take with you
on a weekend trip, there are $\binom{10}{3}$ possibilities. You may
also recall that a formula for $\binom{n}{k}$ is given as follows:
\begin{align*}
\binom{n}{k} = \frac{n!}{k!(n-k)!},
\end{align*}
where $n!$ (read "$n$ factorial") is equal to $1 \cdot 2 \cdot 3
\cdots (n-1) \cdot n$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* For every $n$ and $k$, if $k + 1 \leq n$, then
\begin{equation*}
\binom{n+1}{k+1} = \binom{n}{k+1} + \binom{n}{k}.
\end{equation*}

#+HTML: <hr>
#+LATEX: \horizontalrule

This equation can be proved in terms of the combinatorial
interpretation. Suppose you want to choose $k+1$ shirts out of $n+1$
in your drawer. Set aside one shirt, the blue one. Then you have two
choices: you can either choose $k+1$ shirts from the remaining ones,
with $\binom{n}{k+1}$ possibilities; or you can take the blue one, and
choose $k$ shirts from the remaining ones.

Our goal here, rather, is to prove the theorem using nothing more than
the definition of $\binom{n}{k}$ in terms of factorials.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proof.* We can express the left-hand side of the equation as follows:
\begin{align*}
\binom{n+1}{k+1} & = \frac{(n + 1)!}{(k+1)!((n+1)-(k+1))!} \\
& = \frac{(n + 1)!}{(k+1)!(n - k)!}
\end{align*}
Similarly, we can simplify the right-hand side:
\begin{align*}
\binom{n}{k+1} + \binom{n}{k} & = \frac{n!}{(k+1)!(n-(k+1))!} + \frac{n!}{k!(n-k)!} \\
& = \frac{n!(n-k)}{(k+1)!(n-k-1)!(n-k)} + \frac{(k+1)n!}{(k+1)k!(n-k)!} \\
& = \frac{n!(n-k)}{(k+1)!(n-k)!} + \frac{(k+1)n!}{(k+1)!(n-k)!} \\
& = \frac{n!(n-k + k + 1)}{(k+1)!(n-k)!} \\
& = \frac{n!(n + 1)}{(k+1)!(n-k)!} \\
& = \frac{(n + 1)!}{(k+1)!(n-k)!}
\end{align*}
Thus the left-hand side and the right-hand side are equal.

#+HTML: <hr>
#+LATEX: \horizontalrule

Let us consider a more interesting example, from number
theory. Mathematicians from ancient times have been interested in the
question as to which integers can be written as a sum of two
squares. For example, we can write $2 = 1^1 + 1^1$, $5 = 2^2 + 1^2$,
$13 = 3^2 + 2^2$. If we make a sufficiently long list of these, an
interesting pattern emerges: if two numbers can be written as a sum of
squares, then so can their product. For example, $10 = 5 \cdot 2$, and
we can write $10 = 3^2 + 1^2$. Or $65 = 13 \cdot 5$, and we can write
$65 = 8^2 + 1^2$.

At first, one might wonder whether this is just a coincidence. The
following provides a proof of the fact that it is not.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* Let $x$ and $y$ be any two integers. If $x$ and $y$ are
both sums of squares, then so is $x y$.

*Proof.* Suppose $x = a^2 + b^2$, and suppose $y = c^2 + d^2$. I claim
that
\begin{equation*}
xy = (ac - bd)^2 + (ad + bc)^2.
\end{equation*}
To show this, notice that on the one hand we have
\begin{equation*}
xy = (a^2 + b^2) (c^2 + d^2) = a^2 c^2 + a^2 d^2 + b^2 c^2 + b^2 d^2.
\end{equation*}
On the other hand, we have
\begin{align*}
(ac - bd)^2 + (ad + bc)^2 & = (a^2c^2 - 2abcd + b^2 d^2) + (a^2 d^2 + 2 a b c d + b^2 c^2) \\
  & = a^2 c^2 + b^2 d^2 + a^2 d^2 + b^2 c^2.
\end{align*}
Up to the order of summands, the two right-hand sides are the same.

#+HTML: <hr>
#+LATEX: \horizontalrule


** Exercises

1. Prove the following: if $a$, $b$, and $c$ are any integers such
   that $a \mid b$ and $a \mid c$, then $a \mid b + c$.

2. Give an informal proof of the following theorem : For every integer
   $n$, if $n$ is odd, then $n^2 - 1$ is divisible by 8. (Hint: first
   show that if a number $m$ is even, then either $m$ or $m + 2$ is
   divisible by 4. Also, remember that $n^2 - 1 = (n + 1) (n - 1)$.)

3. Say two integers ``have the same parity'' if they are either both
   even or both odd. Show that if $m$ and $n$ are any two integers,
   then $m + n$ and $m - n$ have the same parity. (Hint: there are
   lots of cases to consider. You can use facts like ``if $m$ and $n$
   are odd, then $m + n$ is even'' as obvious.)

4. Find the last digit of $99^{99}$. Can you also find the last two
   digits of this number?

5. Prove that $50^{22} - 22^{50}$ is divisible by 7.

6. Prove that the equation $n^4+m^4=k^4+3$ has no solutions in the
   integers. (Hint: consider the possible values for both sides modulo
   5.)
