#+Title: Logic and Proof
#+Author: [[http://www.andrew.cmu.edu/user/avigad][Jeremy Avigad]], [[http://www.andrew.cmu.edu/user/rlewis1/][Robert Y. Lewis]],  [[http://www.contrib.andrew.cmu.edu/~fpv/][Floris van Doorn]]

* The Natural Numbers and Induction
:PROPERTIES:
  :CUSTOM_ID: The_Natural_Numbers_and_Induction
:END:

This chapter marks a transition from the abstract to the concrete.
Viewing the mathematical universe in terms of sets, relations, and
strutures gives us useful ways of thinking about mathematical objects
and structures and the relationships between them. At some point,
however, we need to start thinking about /particular/ mathematical
objects and structures, and the natural numbers are a good place to
start. The nineteenth century mathematician Leopold Kronecker once
proclaimed "God created the whole numbers; everything else is the work
of man." By this he meant that the natural numbers (and the integers,
which we will also discuss below) are a fundamental component of the
mathematical universe, and that many other objects and structures of
interest can be constructed from these.

In this chapter, we will consider the natural numbers and the basic
principles that govern them. In Chapter [[file:18_The_Natural_Numbers_and_Induction_in_Lean.org::#The_Natural_Numbers_and_Induction_in_Lean][The Natural Numbers and
Induction in Lean]] we will see that even basic operations like addition
and multiplication can be defined using means described here, and
their properties derived from these basic principles. Our presentation
in this chapter will remain informal, however. In Chapter [[file:19_Elementary_Number_Theory.org::#Elementary_Number_Theory][Elementary
Number Theory]], we will see how these principles play out in one of the
oldest and most venerable branches of mathematics.

** The Principal of Induction

The set of natural numbers is the set 
\[ 
\NN = \{ 0, 1, 2, 3, \ldots \}, 
\]
In the past, conventions have differed as to whether the set of
natural numbers should start with 0 or 1, but these days most
mathematicians take them to start with 0. Logicians often call the
function $s(n) = n + 1$ the /successor/ function, since it maps each
natural number, $n$, to the one that follows it. What makes the
natural numbers special is that they are /generated/ by the natural
numbers, which is to say, the only way to "construct" a natural number
is to start with $0$ and apply the successor function finitely many
times. From a foundational standpoint, we are in danger of running
into a circularity here, because it is not clear how we can explain
what it means to apply a function "finitely many times" without
talking about the natural numbers themselves. But the following
principle, known as the /principle of induction/, describes this
essential property of the natural numbers in a non-circular way.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Principle of Induction.* Let $P$ be any property of natural
numbers. Suppose $P$ holds of zero, and whenever $P$ holds of a
natural number $n$, then it holds of its successor, $n + 1$. Then $P$
holds of every natural number.

#+HTML: <hr>
#+LATEX: \horizontalrule

This reflects the image of the natural numbers as being generated by
zero and the successor operation: by covering the zero and successor
cases, we take care of all the natural numbers.

The principle of induction provides a recipe for proving that every
natural number has a certain property: to show that $P$ holds of every
natural number, show that it holds of $0$, and show that whenever it
holds of some number $n$, it holds of $n + 1$. This form of proof is
called a /proof by induction/. The first required task is called the
/base case/, and the second required task is called the /induction
step/. The induction step requires temporarily fixing a natural number
$n$, assuming that $P$ holds of $n$, and then showing that $P$ holds
of $n + 1$. In this context, the assumption that $P$ holds of $n$ is
called the /inductive hypothesis/.

You can visualize proof by induction as a method of knocking down an
infinite stream of dominoes, all at once. We set the mechanism in
place and known down domino 0, which knocks down domino 1; that knocks
down domino 2, and so on. 

Here is an example of a proof by induction.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* For every natural number $n$, 
\[
1 + 2 + \ldots + 2^n = 2^{n+1} - 1.
\]

*Proof.* By induction on $n$. In the base case, when $n = 0$, we have
$1 = 2^{0+1} - 1$, as required.

For the induction step, fix $n$, and assume
\[
1 + 2 + \ldots + 2^n = 2^{n+1} - 1.
\]
We need to show that this same claim holds with $n$ replaced by $n +
1$. But this is just a calculation:
\begin{align*}
1 + 2 + \ldots + 2^{n+1} & = (1 + 2 + \ldots + 2^n) + 2^{n+1} \\
& = 2^{n+1} - 1 + 2^{n+1} \\
& = 2 \cdot 2^{n+1} - 1 \\
& = 2^{n+2} - 1.
\end{align*}

In the notation of first-order logic, if we write $P(n)$ to mean that
$P$ holds of $n$, we could express the principle of induction as
follows:
\[
P(0) \wedge \fa n (P(n) \to P(n + 1)) \to \fa n P(n).
\]
But notice that the principle of induction says that the axiom holds
/for every property/ $P$, which means that we should properly use a
universal quantifier for that, too:
\[
\fa P (P(0) \wedge \fa n (P(n) \to P(n + 1)) \to \fa n P(n)).
\]
Quantifying over properties takes us out of the realm of first-order
logic; induction is therefore a second-order principle.

The pattern for a proof by induction is expressed even more naturally
by the following natural deduction rule:
\begin{center}
\AXM{P(0)}
\AXM{}
\RLM{1}
\UIM{P(n)}
\noLine
\UIM{\vdots}
\noLine
\UIM{P(n+1)}
\BIM{\fa n P(n)}
\DP
\end{center}
You should think about how some of the proofs in this chapter could be
represented formally using natural deduction proofs. 

For another example of a proof by induction, let us derive a formula
that, given any finite set $S$, determines the number of subsets of
$S$. For example, there are four subsets of the two-element set $\{1,
2\}$, namely $\emptyset$, $\{1\}$, $\{2\}$, and $\{1, 2\}$. You should
convince yourself that there are eight subsets of the set $\{1, 2,
3\}$. The following theorem establishes the general pattern.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* For any finite set $S$, if $S$ has $n$ elements, then there
are $2^n$ subsets of $S$.

*Proof.* We use induction on $n$. In the base case, there is only one
set with $0$ elements, the empty set, and there is exactly one subset
of the empty set, as required.

In the inductive case, suppose $S$ has $n + 1$ elements. Let $a$ be
any element of $S$, and let $S'$ be the remaining $n$ elements. In
order to count the subsets of $S$, we divide them into two
groups. 

First, we consider the subsets of $S$ that don't contain
$a$. These are exactly the subsets of $S'$, and by the inductive
hypothesis, there are $2^n$ of those.

Next we consider the subsets of $S$ that /do/ contain $a$. Each of
these is obtained by choosing a subset of $S'$ and adding $a$. Since
there are $2^n$ subsets of $S'$, there are $2^n$ subsets of $S$ that
contain $a$.

Taken together, then, there are $2^n + 2^n = 2^{n+1}$ subsets of $S$,
as required.

#+HTML: <hr>
#+LATEX: \horizontalrule

We have seen that there is a correspondence between properties of a
domain and subsets of a domain. For every property $P$ of natural
numbers, we can consider the set $S$ of natural numbers with that
property, and for every set of natural numbers, we can consider the
property of being in that set. For example, we can talk about the
property of being even, or talk about the set of even numbers. Under
this correspondence, the principle of induction can be cast as
follows:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Principle of Induction.* Let $S$ be any set of natural numbers that
contains $0$ and is closed under the successor operation. Then $S =
\NN$.

#+HTML: <hr>
#+LATEX: \horizontalrule

Here, saying that $S$ is "closed under the successor operation" means
that whenever a number $n$ is in $S$, so is $n + 1$.

** Variants of Induction

In this section, we will consider variations on the principle of
induction that are often useful. It is important to recognize that
each of these can be justified using the principle of induction as
stated in the last section, so they need not be taken as fundamental.

The first one is no great shakes: instead of starting from $0$, we can
start from any natural number, $m$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Principle of Induction from a Starting Point.* Let $P$ be any
property of natural numbers, and let $m$ be any natural
number. Suppose $P$ holds of $m$, and whenever $P$ holds of a natural
number $n$ greater than or equal to $m$, then it holds of its
successor, $n + 1$. Then $P$ holds of every natural number greater
than or equal to $m$.

#+HTML: <hr>
#+LATEX: \horizontalrule

Assuming the hypotheses of this last principle, if we let $P'(n)$ be
the property "$P$ holds of $m + n$," we can prove that $P'$ holds of
every $n$ by the ordinary principle of induction. But this means that
$P$ holds of every number greater than or equal to $m$.

Here is one example of a proof using this variant of induction.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* For every natural number $n \geq 5$, $2^n > n^2$.

*Proof.* By induction on $n$. When $n = 5$, we have $2^n = 32 > 25 =
n^2$, as required.

For the induction step, suppose $n \ge 5$ and $2^n > n^2$. Since $n$
is greater than or equal to $5$, we have $2n + 1 \leq 3 n \leq n²$,
and so
\begin{align*}
(n+1)² &= n^2 + 2n + 1 \\
  & \leq n^2 + n^2 \\
  & < 2^n + 2^n
\end{align*}

#+HTML: <hr>
#+LATEX: \horizontalrule

For another example, let us derive a formula for the sum total of the
angles in a convex polygon. A polygon is said to be /convex/ if every
line between two vertices stays inside the polygon. We will accept,
without proof, the visually obvious fact that one can subdivide any
convex polygon with more than three sides into a triangle and a convex
polygon with one fewer side, namely, by closing off any two consecutive
sides to form a triangle. We will also accept, without proof, the
basic geometric fact that the sum of the angles of any triangle is 180
degrees.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* For any $n \geq 3$, the sum of the angles of any convex
$n$-gon is $180(n - 2)$.

*Proof.* In the base case, when $n = 3$, this reduces to the statement
that the sum of the angles in any triangle is 180 degrees.

For the induction step, suppose $n \geq 3$, and let $P$ be a convex
$(n+1)$-gon. Divide $P$ into a triangle and an $n$-gon. By the
inductive hypotheses, the sum of the angles of the $n$-gon is
$180(n-2)$ degrees, and the sum of the angles of the triangle is $180$
degrees. The measures of these angles taken together make up the sum
of the measures of the angles of $P$, for a total of $180(n-2) + 180 =
180(n-1)$ degrees.

#+HTML: <hr>
#+LATEX: \horizontalrule

For our second example, we will consider the principle of /complete
induction/, also sometimes known as /total induction/.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Principle of Complete Induction.* Let $P$ be any property that
satisfies the following: for any natural number $n$, whenever $P$
holds of every number less than $n$, it also holds of $n$. Then $P$
holds of every natural number.

#+HTML: <hr>
#+LATEX: \horizontalrule

Notice that there is no need to break out a special case for zero: for
any property $P$, $P$ holds of all the natural numbers less than zero,
for the trivial reason that there aren't any! So, in particular, any
such property automatically holds of zero.

Notice also that such a property $P$ holds of every number less than
$n$, then it also holds of every number less than $n + 1$ (why?). So,
for such a $P$, the ordinary principle of induction implies that for
every natural number $n$, $P$ holds of every natural number less than
$n$. But this is just a roundabout way of saying that $P$ holds of
every natural number. In other words, we have justified the principle
of complete induction using ordinary induction.

To use the principle of complete induction we merely have to
let $n$ be any natural number and show that $P$ holds of $n$, assuming
that it holds of every smaller number. Compare this to the ordinary
principle of induction, which requires us to show $P (n + 1)$ assuming
only $P(n)$. The following example of the use of this principle is
taken verbatim from the introduction to this book:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* Every natural number greater than equal to 2 can be written
as a product of primes.

*Proof.* We proceed by induction on $n$. Let $n$ be any natural number
greater than 2. If $n$ is prime, we are done; we can consider $n$
itself as a product with one term. Otherwise, $n$ is composite, and we
can write $n = m \cdot k$ where $m$ and $k$ are smaller than $n$ and
greater than 1. By the inductive hypothesis, each of $m$ and $k$ can
be written as a product of primes, say
\[
m = p_1 \cdot p_2 \cdot \ldots \cdot p_u
\]
and
\[
k = q_1 \cdot q_2 \cdot \ldots \cdot q_v.
\]
But then we have
\[
n = m \cdot k = p_1 \cdot p_2 \cdot \ldots \cdot p_u \cdot q_1 \cdot
q_2 \cdot \ldots \cdot q_v,
\]
a product of primes, as required.

#+HTML: <hr>
#+LATEX: \horizontalrule

Finally, we will consider another formulation of induction, known as
the least element principle.

#+HTML: <hr>
#+LATEX: \horizontalrule

*The Least Element Principle.* Suppose $P$ is some property of natural
numbers, and suppose $P$ holds of some $n$. Then there is a smallest
value of $n$ for which $P$ holds.

#+HTML: <hr>
#+LATEX: \horizontalrule

In fact, using classical reasoning, this is equivalent to the
principle of complete induction. To see this, consider the
contrapositive of the statement above: "if there is no smallest value
for which $P$ holds, then $P$ doesn't hold of any natural number." Let
$Q(n)$ be the property $P$ does /not/ hold of $n$. Saying that there
is no smallest value for which $P$ holds means that, for every $n$, if
$P$ holds at $n$, then it holds of some number smaller than $n$; and
this is equivalent to saying that, for every $n$, if $Q$ doesn't hold
at $n$, then there is a smaller value for which $Q$ doesn't hold. And
/that/ is equivalent to saying that if $Q$ holds for every number less
than $n$, it holds for $n$ as well. Similarly, saying that $P$ doesn't
hold of any natural number is equivalent to saying that $Q$ holds of
every natural number. In other words, replacing the least element
principle by its contrapositive, and replacing $P$ by "not $Q$," we
have the principle of complete induction. Since every statement is
equivalent to its contrapositive, and every predicate as its negated
version, the two principles are the same.

It is not surprising, then, that the least element principle can be
used in much the same way as the principle of complete
induction. Here, for example, is a formulation of the previous proof
in these terms. Notice that it is phrased as a proof by contradiction.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* Every natural number greater than equal to 2 can be written
as a product of primes.

*Proof.* Suppose, to the contrary, there some natural number greater
than or equal to 2 cannot be written as a product of primes. By the
least element principle, there is a smallest such element; call it
$n$. Then $n$ is not prime, and since it is greater than or equal to
2, it must be composite. Hence we can write $n = m \cdot k$ where $m$
and $k$ are smaller than $n$ and greater than 1. By
the assumption on $n$, each of $m$ and $k$ can be written as a product of
primes, say
\[
m = p_1 \cdot p_2 \cdot \ldots \cdot p_u
\]
and
\[
k = q_1 \cdot q_2 \cdot \ldots \cdot q_v.
\]
But then we have
\[
n = m \cdot k = p_1 \cdot p_2 \cdot \ldots \cdot p_u \cdot q_1 \cdot
q_2 \cdot \ldots \cdot q_v,
\]
a product of primes, contradicting the fact that $n$ cannot be written
as a product of primes.

#+HTML: <hr>
#+LATEX: \horizontalrule

Here is another example:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* Every natural number is interesting.

*Proof.* Suppose, to the contrary, some natural number is
uninteresting. Then there is a smallest one, $n$. In other words, $n$
is the smallest uninteresting number. But that is really interesting!
Contradiction.

#+HTML: <hr>
#+LATEX: \horizontalrule

** Recursive Definitions
:PROPERTIES:
  :CUSTOM_ID: Recursive_Definitions
:END:

Supose I tell you that I have a function $f : \NN \to \NN$ in mind,
satisfying the following properties:
\begin{align*}
 f(0) & = 1 \\
 f(n + 1) & = 2 \cdot f(n)
\end{align*}
What can you infer about $f$? Try calculating a few values:
\begin{align*}
  f(1) & = f(0 + 1) = 2 \cdot f(0) = 2 \\
  f(2) & = f(1 + 1) = 2 \cdot f(1) = 4 \\
  f(3) & = f(2 + 1) = 2 \cdot f(2) = 8
\end{align*}
It soon becomes apparent that for every $n$, $f(n) = 2^n$. 

What is more interesting is that the two conditions above specify
/all/ the values of $f$, which is to say, there is exactly one
function meeting the specification above. In fact, it does not matter
that $f$ takes values in the natural numbers; it could take values in
any other domain. All that is needed is a value of $f(0)$ and a way
to compute the value of $f(n+1)$ in terms of $n$ and $f(n)$. This is
what the principle of definition by recursion asserts:

#+HTML: <hr>
#+LATEX: \horizontalrule

*Principle of Definition by Recursion*. Let $A$ be any set, and
suppose $a$ is in $A$, and $g : \NN \times A \to A$. Then there is a
unique function $f$ satisfying the following two clauses:
\begin{align*}
 f(0) & = a \\
 f(n + 1) & = g(n, f(n)).
\end{align*}

#+HTML: <hr>
#+LATEX: \horizontalrule

The principle of recursive definition makes two claims at once: first,
that there is a function $f$ satisfying the clauses above, and,
second, that any two functions $f_1$ and $f_2$ satsifying those
clauses are equal, which is to say, they have the same values for
every input. In the example above, $A$ is just $\NN$ and $g(n, f(n)) =
2 \cdot f(n)$.

In some axiomatic frameworks, the principle of recursive definition can be
justified using the principle of induction. In others, the principle
of induction can be viewed as a special case of the principle of
recursive definition. For now, we will simply take both to be
fundamental properties of the natural numbers.

As another example of a recursive definition, consider the function
$h : \NN \to \NN$ defined recursively by the following clauses:
\begin{align*}
  g(0) & = 1 \\
  g(n+1) & = (n + 1) \cdot g(n)
\end{align*}
Try calculating the first few values. Unwrapping the definition, we
see that $g(n) = 1 \cdot 2 \cdot 3 \cdots (n-1) \cdot n$ for every
$n$; indeed, definition by recursion is usually the proper way to make
expressions using "\ldots" precise. The value $g(n)$ is read "$n$
factorial," and written $n!$.

Indeed, summation notation
\[
\sum_{i < n} f (i) = f(0) + f(1) + \ldots + f(n-1)
\]
and product notation
\[
\prod_{i < n} f (i) = f(0) \cdot f(1) \cdot \cdots \cdot f(n-1)
\]
can also be made precise using recursive definitions. For example, the
function $k(n) = \sum_{i < n} f (i)$ can be defined recursively as
follows:
\begin{align*}
k(0) &= 0 \\
k(n+1) &= k(n) + f(n + 1)
\end{align*}

Induction and recursion are complementary principles, and typically
the way to prove something about a recursively defined function is to
use the principle of induction. For example, the following theorem
provides a formulas for the sum $1 + 2 + \ldots + n$, in terms of $n$.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Theorem.* For every $n$, $\sum_{i < n + 1} i = n (n + 1) / 2$.

*Proof.* In the base case, when $n = 0$, both sides are equal to $0$.

In the inductive step, we have
\begin{align*}
\sum_{i < n + 2} i & = \left(\sum_{i < n + 1} i\right) + (n + 1) \\
& = n (n + 1) / 2 + n + 1 \\
& = \frac{n^2 +n}{2} + \frac{2n + 2}{2} \\
& = \frac{n^2 + 3n + 2}{2} \\
& = \frac{(n+1)(n_2)}{2}.
\end{align*}

#+HTML: <hr>
#+LATEX: \horizontalrule

There are just as many variations on the principle of recursive
definition as there are on the principle of induction. For example, in
analogy to the principle of complete induction, we can specify a value
of $f(n)$ in terms of the values that $f$ takes at all inputs smaller
than $n$. When $n \geq 2$, for example, the following definition
specifies that value of a function $\fn{fib}(n)$ in terms of its two
predecessors:
\begin{align*}
  \fn{fib}(0) & = 0 \\
  \fn{fib}(1) & = 1 \\
  \fn{fib}(n+2) & = \fn{fib}(n + 2) + \fn{fib}(n).
\end{align*}
Calculating the values of $\fn{fib}$ on $0, 1, 2, \ldots$ we obtain
\[
0, 1, 1, 2, 3, 5, 8, 13, 21, \ldots
\]
where, after the second number, each successive number is the sum of
the two values preceding it. This is known as the \emph{Fibonacci
sequence}, and the corresponding numbers are known as the
\emph{Fibonacci numbers}. An ordinary mathematical presentation would
write $F_n$ instead of $\fn{fib}(n)$ and specify the sequence with the
following equations:
\[
 F_0 = 0, \quad F_1 = 1, \quad F_{n+2} = F_{n+1} + F_n
\]
But you can now recognize such a specification as an implicit appeal
to the principle of definition by recursion. We ask you to prove some
facts about the Fibonacci sequence in the exercises below.

# include the Fibonacci story

** Arithmetic on the Natural Numbers
:PROPERTIES:
  :CUSTOM_ID: Arithmetic_on_the_Natural_Numbers
:END:

In the next chapter, we will it is even possible to define addition
and multiplication recursively, and to establish most of their basic
properties using the principle of recursion. This is important from a
foundational perspective, in which, as much as possible, we want to
ground our reasoning on a small number of fundamental principles. Just
as the foundations of a building are below ground, however, the
foundations of mathematics should only be visible when we choose to go
down to the basement and look around. In this section, therefore, we
summarize the basic properties of natural numbers that play a role in
day-to-day mathematics. In an ordinary mathematical argument or
calculation, they can be used without explicit justification.

\begin{align*}
m + n &= n + m &&\text{(commutativity of addition)}\\
m + (n + k) &= (m + n) + k &&\text{(associativity of addition)}\\
n + 0 &= n &&\text{($0$ is a neutral element for addition)}\\
n \cdot m &= m \cdot n &&\text{(commutativity of multiplication)}\\
m \cdot (n \cdot k) &= (m \cdot n) \cdot k 
    &&\text{(associativity of multiplication)}\\
n \cdot 1 &= n &&\text{($1$ is an neutral element for multiplication)}\\
n \cdot (m + k) &= n \cdot m + n \cdot k &&\text{(distributivity)}\\
n \cdot 0 &= 0 &&\text{($0$ is an absorbing element for multiplication)}
\end{align*}
We also have the following properties:
- $n + 1 \neq 0$;
- if $n + k = m + k$ then $n = m$;
- if $n \cdot k = m \cdot k$ and $k \neq 0$ then $n = m$.

If we define $m < n$, "$m$ is less than $n$," to mean that there
exists a $k$ such that $m + k + 1 = n$, then the less-than relation is
a strictly inequality, satisfying all of the following properties:

- $n < n$ is never true (/irreflexivity/);
- if $n < m$ and $m < k$ then $n < k$ (/transitivity/);
- for all $n$ and $m$, either $n < m$, $n = m$ or 
    $m < n$ is true (/trichotomy/);
- if $n < m$ then $n + k < m + k$;
- if $k > 0$ and $n < m$ then $nk < mk$;
- if $m > n$ then $m = n + 1$ or $m > n + 1$;
- for all $n$, $n = 0$ or $n > 0$.

The relation $x \le y$, read "$x$ is less than or equal to $y$," is
defined to mean just that, that is, the $x$ is less than $y$ or $x$ is
equal to $y$. The following properties follow from this definition and
the properties of $<$:
- $n \le n$ (/reflexivity/);
- if $n \le m$ and $m \le k$ then $n \le k$ (/transitivity/);
- if $n \le m$ and $m \le n$ then $n = m$ (/antisymmetry/);
- for all $n$ and $m$, either $n \le m$ or $m \le n$ is true (/totality/);
- if $n \le m$ then $n + k \le m + k$;
- if $n \le m$ then $nk \le mk$;
- if $m \ge n$ then $m = n$ or $m \ge n + 1$;
- $0 \le n$.

Here are some additional properties of $<$ and $\le$:
- $n < m$ and $m < n$ cannot both hold (/asymmetry/);
- $n + 1 > n$;
- if $n < m$ and $m \le k$ then $n < k$;
- if $n \le m$ and $m < k$ then $n < k$;
- if $m > n$ then $m \ge n + 1$;
- if $m \ge n$ then $m + 1 > n$;
- if $n + k < m + k$ then $n < m$;
- if $nk < mk$ then $k > 0$ and $n < m$.
These can be proved from the ones above. Moreover, the collection of
principles we have just seen can be used to justify basic facts about
the natural numbers, which are again typically taken for granted in
informal mathematical arguments.

#+HTML: <hr>
#+LATEX: \horizontalrule

*Proposition.* If $n$ and $m$ are natural numbers such that $n + m =
0$, then $n = m = 0$.

*Proof.* We first prove that $m = 0$. We know that $m = 0$ or $m >
0$. Suppose that $m > 0$ Then $n + m > n + 0 = n$. Since $n \ge 0$, we
conclude that $n + m > 0$, which is in contradiction with $n + m =
0$. Since $m > 0$ leads to a contradiction, the other option that $m =
0$ must hold.

Now we can easily conclude that $n = 0$ using the following chain of
equalities $n = n + 0 = n + m = 0$. Hence $n = m = 0$.

*Proposition.* If $n$ is a natural number such that $n < 3$, then $n =
0$, $n = 1$ or $n = 2$.

*Proof.* In this proof we repeatedly use the property that if $m > n$
then $m = n + 1$ or $m > n + 1$. Since $2 + 1 = 3 > n$, we conclude
that either $2 + 1 = n + 1$ or $2 + 1 > n + 1$. In the first case we
conclude $n = 2$, and we are done. In the second case we conclude $2 >
n$. Now we conclude that either $2 = n + 1$, or $2 > n + 1$. In the
first case, we conlude $n = 1$, and we are done. In the second case,
we conclude $1 > n$. One last time we use the property mentioned
above, to conclude that either $1 = n + 1$ or $1 > n + 1$. In the
first case, we conclude $n = 0$, and we are once again done. In the
second case, we conclude that $0 > n$. This leads to a contradiction,
since now $0 > n \ge 0$, hence $0 > 0$, which contradicts the
irreflexivity of $>$.

#+HTML: <hr>
#+LATEX: \horizontalrule

** The Integers
:PROPERTIES:
  :CUSTOM_ID: The_Integers
:END:

The natural numbers are designed for counting discrete quantities, but
they suffer an annoying drawback: if is possible to subtract $n$ from
$m$ if $n$ is less than or equal to $m$, but not if $m$ is greater
than $n$. The /integers/, $\ZZ$, extends the natural numbers with
negative values to make it possible to carry out substraction in full:
\[
\ZZ = \{ \ldots, -3, -2, -1, 0, 1, 2, 3, \ldots \} 
\]
We will see in a later chapter that the integers can be extended to
the /rational numbers/, the /real numbers/, and the /complex numbers/,
each of which serves useful purposes. For dealing with discrete
quantities, however, the integers will get us pretty far.

You can think of the integers as consisting of two copies of the
natural numbers, a positive one and a negative one, sharing a common
zero. Conversely, once we have the integers, you can think of the
natural numbers as consisting of the nonnegative integers, that is,
the itnegers that are greater than or equal to $0$. Most
mathematicians blur the distinction between the two, though we will
see that in Lean, for example, the natural numbers and the integers
represent two different data types.

Most of the properties of the natural numbers that were enumerated in
the last section hold of the integers as well, but not all. For
example, it is no longer the case that $n + 1 \neq 0$ for every $n$,
since the claim is false for $n = -1$. For another example, it is not
the case that every integer is either equal to $0$ or greater than
$0$, since this fails to hold of the negative integers.

The key property that the integers enjoy, which sets them apart from
the natural numbers, is that for every integer $n$ there is a value
$-n$ with the property that $n + (-n) = 0$. The value $-n$ is called
the /negation/ of $n$. We define subtraction $n - m$ to be $n +
(-m)$. For any integer $n$, we also define the /absolute value/ of
$n$, written $|n|$, to be $n$ if $n \geq 0$, and $-n$ otherwise. 

Proof by induction no longer holds, because induction does not cover
the negative numbers. But we can use induction to show that a property
holds of every nonnegative integer, for example. Moreover, we know
that every negative integer is the negation of a positive one. Proofs
involving the integers therefore break down into two cases, for
example, using one case to cover the nonnegative integers, and another
to cover the negative ones.

** Exercises

1. Write the principle of complete induction using the notation of
   symbolic logic. Also write the least element principle this way,
   and use logical manipulations to show that the two are equivalent.

2. Show that for every $n$, $0^2 + 1^2 + 2^2 + \ldots n^2=
   \frac{1}{6}n(n+1)(n+2)$.

3. Show that for every $n$, $0^3 + 1^3 + \ldots + n^3 = \frac{1}{4}
   n^2 (n+1)^2$.

4. Given the definition of the Fibonacci numbers in Section [[#Recursive_Definitions][Recursive
   Definitions]], prove Cassini's identity: for every $n$, $F^2_{n+1} -
   F_{n+2} F_n = (-1)^n$. Hint: in the induction step, write
   $F_{n+2}^2$ as $F_{n+2}(F_{n+1} + F_n)$.

5. Prove $\sum_{i < n} F_{2i+1} = F_{2n}$.

6. Prove the following two identities:

   - $F_{2n+1} = F^2_{n+1} + F^2_n$
   - $F_{2n+2} = F^2_{n+2} - F^2_n$

   Hint: use induction on $n$, and prove them both at once. In the
   induction step, expand $F_{2n+3} = F_{2n+2} + F_{2n+1}$, and
   similarly for $F_{2n+4}$. Proving the second equation is
   especially tricky. Use the inductive hypothesis and the first
   identity to simplify the left-hand side, and repeatedly unfold the
   Fibonacci number with the highest index and simplify the equation
   you need to prove. (When you have worked out a solution, write a
   clear equational proof, calculating in the ``forwards''
   direction.)

7. Following the example in Section [[#Arithmetic_on_the_Natural_Numbers][Arithmetic on the Natural Numbers]],
   prove that if $n$ is a natural number and $n < 5$, then $n$ is one
   of the values $0, 1, 2, 3$, or $4$.

8. Prove that if $n$ and $m$ are natural numbers and $n m = 1$, then
   $n = m = 1$.

   This is tricky. First show that $n$ and $m$ are greater than $0$,
   and hence greater than or equal to $1$. Then show that if either
   one of them is greater than $1$, then $n m > 1$.

9. Prove the following properties of negation and subtraction on the
   integers, using only the properties of negation and subtraction
   given in Section [[#The_Integers][The Integers]].

   - if $n + m = 0$ then $m = -n$;
   - $-0 = 0$;
   - if $-n = -m$ then $n = m$;
   - $m + (n - m) = n$;
   - $-(n + m) = -n - m$;
   - if $m < n$ then $n - m > 0$;
   - if $m < n$ then $-m > -n$;
   - $n \cdot (-m) = -nm$;
   - $n(m - k) = nm - nk$;
   - if $n < m$ then $n - k < m - k$.



