#+Title: Logic and Proof
#+Author: [[http://www.andrew.cmu.edu/user/avigad][Jeremy Avigad]], [[http://www.andrew.cmu.edu/user/rlewis1/][Robert Y. Lewis]],  [[http://www.contrib.andrew.cmu.edu/~fpv/][Floris van Doorn]]

* Number Systems
:PROPERTIES:
  :CUSTOM_ID: Number_Systems
:END:

Formal logic developed, in part, as a framework to solidify the foundation of mathematical
reasoning. With solid /methods/ of reasoning, then, it seems reasonable to ask for something
solid to reason /about/. Numbers -- natural numbers, integers, real numbers, and the like --
shouldn't be taken for granted (although some might disagree!). Rather, they should be
/shown/ to exist, or /constructed/ from more basic principles.

What these basic principles are, exactly, depends on one's choice of logical framework.
In this chapter, we will look at how the various number structures are defined both in
set theory and in Lean's type theory.

** The Natural Numbers
At this point, you must be familiar with the set $\NN$ of natural numbers $\{0, 1, 2, \ldots\}$.
They form the basis of many, many further mathematical definitions. In fact, the other
number structures we'll look at in this chapter are all based on $\NN$.

The natural numbers have two "defining" properties. First of all, there is a /first/
natural number, 0. Second of all, for each natural number $n$, there is a unique /successor/,
the natural number $n + 1$. (We often write $succ n$ instead.) These properties alone don't
distinguish $\NN$: both are true in $\RR$, for example. The natural numbers must be
minimal, in some sense: there is no subset of $\NN$ (using the same successor function)
that has both of these properties. A more intuitive way of thinking about this is that the
natural numbers have "nothing extra": they contain a single infinite chain of successor
elements starting at 0, and nothing else.

To define the natural numbers in set theory, then, we want to find a minimal set with these
properties. (Remember that in set theory, every object is a set, so our natural numbers will
be sets: 0, 1, etc. are names for particular sets.) For the sake of clarity, we will use
refer to the set representation of a natural number $n$ as the /numeral/ $\bar n$.

Set theory gives us relatively few "starting points." What set should we pick to be the
numeral $\bar 0$?
The "obvious" choice is the empty set, $\emptyset$. Really, any set would work, but we
might as well keep things as simple as possible.

Defining the successor function takes a little more care, although there are multiple ways
to do it. We will take the following
approach: for a numeral $\bar n$, define $succ \bar n = \bar n \cup \{\bar n\}$. Written in the abstract,
this seems strange, but consider this list of the first few numerals:

- $\bar 0 = \emptyset$
- $\bar 1 = \bar 0 \cup \{\bar 0\} = \emptyset \cup \{\emptyset\} = \{\emptyset\}$
- $\bar 2 = \bar 1 \cup \{\bar 1\} = \{\emptyset\} \cup \{ \{\emptyset\} \} = \{ \emptyset, \{\emptyset\} \}$
- $\bar 3 = \bar 2 \cup \{\bar2\} = \{ \emptyset, \{\emptyset\}, \{ \emptyset, \{\emptyset\} \} \}$

Each numeral contains every element of the numeral before it, plus that previous numeral itself.
Count how many elements each numeral contains: the cardinality of $\bar n$ is exactly $n$.
Therefore, $|succ \bar n| = n + 1$, which tells us our successor function is injective: if
$succ \bar n = succ \bar m$, then $\bar n = \bar m$ and $n = m$.

We define $\NN$ to be the set of all such numerals $\{\bar 0, \bar 1, \bar 2, \ldots\}$.
(The existence of this infinite set can be shown using the axioms of set theory.) Of course,
the natural numbers aren't so useful without operations like $+$, $\cdot$, and the like;
luckily it is possible to define these operations based on the successor operation.

We mentioned that there are different ways to define the successor. Another historically
relevant option is to define $succ \bar n = \{ \bar n \}$. Thus, we have
$0 = \emptyset$, $1 = \{\emptyset\}$, $2 = \{\{\emptyset\}\}$, and so on. The full set $\NN$
that we obtain from this construction is, obviously, a different set from the first. Why
should we say that one is the "true" $\NN$? Philosophers have puzzled over this question,
but one appealing answer is that we shouldn't. What matters about the structure $\NN$ isn't
exactly which set underlies it; we really care about the fact that has 0 and $succ$,
that we can add and multiply elements, that $\NN$ is an instance of an algebraic structure
called a /semiring/, and so on. All of these properties hold regardless of /which/ concrete
definition we choose. So once we have shown that there is /some/ set with the right properties,
we "abstract away" from the details of its definition and just work with these properties.

[Blend in to type theory?]

We characterized the natural numbers as the smallest set having an "initial" element 0 and
an injective "successor" operation $succ$. In our set theoretic definition, we had to
define these and show that our definition for $succ$ was, in fact, injective. Conveniently,
the version of type theory used in Lean allows us to blend these two steps into one. There
is a built-in mechanism, called an /inductive/ definition, for defining the smallest type
with certain properties.

#+BEGIN_SRC lean
namespace nat_definition -- (ignore this line!)

inductive nat : Type :=
| zero : nat
| succ : nat → nat
#+END_SRC

Lean assumes that the /constructors/ zero and succ are injective, and that there is no way
to create an element of type nat without using one of these constructors. Thus this type
has the properties we expect of the natural numbers. We can go on to define addition as
follows:

#+BEGIN_SRC lean
namespace nat_definition -- (ignore this line!)

inductive nat :=
| zero : nat
| succ : nat → nat

open nat_definition.nat -- (ignore this line!)

--BEGIN
definition add : nat → nat → nat
| add n zero     := n
| add n (succ m) := succ (add n m)
--END
#+END_SRC

This is a "definition by cases." adding zero to any natural number $n$ gives back $n$;
if $m$ is a natural number, adding $succ m$ to $n$ gives $succ (add n m)$. We can write
similar definitions for multiplication and other operations.

[Should we discuss semirings?]

** Integers and rationals
Once the natural numbers are defined, it is easy to construct the integers $\ZZ$. There are
many ways to do it. In set theory, one option is to define $\ZZ$ to be the set of ordered
pairs $\langle s, n \rangle$, where $s \in \{0, 1\} \subset \NN$ and $n \in \NN$. The pair
$\langle 0, n \rangle$ represents the positive integer $n$, and the pair
$\langle 1, n \rangle$ represents the negative integer $-(n + 1)$. (We add 1 here to
avoid multiple representations of the integer 0.) A similar approach works in type theory.

A rational number consists of a numerator and a nonzero denominator. It's tempting, then,
to define the set $\QQ$ to be the set of ordered pairs $\langle n, d \rangle$, where
$n \in \ZZ$ and $d \in \NN^+$ (the set of positive natural numbers). But this contains
"repeat" elements: $\langle 1, 2 \rangle$ and $\langle 2, 4 \rangle$ are different sets
but represent the same rational number. For now, we will call this set of pairs $Q$.

We say that $\langle n_1, d_1 \rangle$ and $\langle n_2, d_2 \rangle$ are /equivalent/ if
$n_1 \cdot (d_2 + 1) = n_2 \cdot (d_1 + 1)$. For $p \in Q$, the /equivalence class/ of $p$ is the set
$\{q \in Q : p \text{ and } q \text{ are equivalent} \}$. Notice that an equivalence class
is simply a subset of $Q$ whose elements represent the same rational number, and that every
pair which represents this rational number is an element of that equivalence class.
We define $\QQ$ to be the set of all such equivalence classes in $Q$.

This process is known as taking the /quotient/ of a set with respect to an equivalence
relation, and appears quite frequently in mathematics. There is a similar operation allowed
in type theory: to define the type rat, we take the quotient of the type $bool \times nat$
with respect to the appropriate equivalence relation.

[Discuss rings and fields?]

** Reals

Constructing the real numbers $\RR$ takes significantly more work than $\ZZ$ or $\QQ$.
Historically, two approaches have been used most often; in most settings they are equivalent,
although in some logics they produce sets with somewhat different properties. Here we will
describe the approach using /Dedekind cuts/. Both this definition and the alternate, using
/Cauchy sequences/, can be formalized in type theory; how direct the translation is depends
on what kind of type theory is being used.

A Dedekind cut is an ordered pair $\langle A, B \rangle$ of sets of rational numbers with the
following properties:

- Every rational number $q$ is in either $A$ or $B$.
- Each $a \in A$ is less than every $b \in B$.
- There is no greatest element of $A$.
- $A$ and $B$ are both nonempty

The first two properties show why we call this pair a "cut." The set $A$ contains all of
the rational numbers to the left of some mark on the number line, and $B$ all of the points
to the right. The third property tells us something about what happens exactly at that mark.
But there are two possibilities: either $B$ has a least element, or it doesn't. Picturing
the situation where $A$ has no greatest element and $B$ has no least element may be tricky,
but consider the example $A = \{x \in \QQ : x^2 < 2\}$ and $B = \{x \in \QQ : x^2 > 2\}$.
There is no rational number $q$ such that $q^2 = 2$, but there are rational numbers on
either side that are arbitrarily close; thus neither $A$ nor $B$ contains an endpoint.

We define $\RR$ to be the set of Dedekind cuts. A Dedekind cut $\langle A, B \rangle$
corresponds to a rational number $q$ if $q$ is the least element of $B$, and to an irrational
number if $B$ has no least element. It is straightforward to define addition on $\RR$:
$$\langle A_1, B_1 \rangle + \langle A_2, B_2 \rangle = \langle \{a_1 + a_2 : a_1 \in A_1,
 a_2 \in A_2 \}, \{b_1 + b_2 : b_1 \in B_1, b_2 \in B_2 \} \rangle .$$
Multiplication is defined similarly.

We think of the real numbers as the rational numbers with the "gaps" filled in. This
intuition is precisely what the Dedekind cut definition tries to capture: a "gap" in the
rationals is present when two sets without endpoints can cover the entire rational line.
The set $\RR$ of Dedekind cuts /completes/ $\QQ$ by adding elements to represent these
gaps. Notice that applying this "completening" process again to $\RR$ does not add any
new elements: for any $A, B \subset \RR$ with the same properties as before, $B$ must have
a least element. This is why we say that the real line is complete.
