#+Title: Logic and Proof
#+Author: [[http://www.andrew.cmu.edu/user/avigad][Jeremy Avigad]], [[http://www.andrew.cmu.edu/user/rlewis1/][Robert Y. Lewis]],  [[http://www.contrib.andrew.cmu.edu/~fpv/][Floris van Doorn]]

* Real Numbers and Analysis
:PROPERTIES:
  :CUSTOM_ID: Real_Numbers_and_Analysis
:END:

Mathematicians often distinguish the /discrete/ from the /continuous/. The natural numbers and the integers 
fall into the former category. Roughly speaking, this is because there is "space" between any two distinct
integers: 0 and 1 are not equal, but there is no integer that falls between them. (The study of topology makes
this distinction more precise.)

The rational numbers are different. If $a$ and $b$ are distinct rationals with $a < b$, then we know that
$a < \frac{b - a}{2} < b$. Put another way, for any rational $a$, there must be another rational arbitrarily close
to $a$: for any $\epsilon \in \QQ$, there is a $b \in \QQ$ such that $|a - b| < \epsilon$. We say that the
rational numbers are /dense/.

Despite being dense, though, there are still "gaps" in the rationals. Recall that any finite decimal number 
(e.g. 3.141) is rational, and consider the (infinite) decimal representation of $\sqrt{2}$, 1.41421356.... Define
a sequence of rational numbers $\{q_i\}_{i \in \NN}$, such that $q_i$ includes the first $i+1$ digits of $\sqrt{2}$:
$q_0=1, q_1=1.4, q_2 = 1.41$ and so on. This is an increasing sequence, and the distance between subsequent
entries in the sequence gets smaller as $i$ grows. Nonetheless, it has no /limit point/. For any rational number
$q$, either the sequence "crosses" $q$ -- there is some $n$ such that, for all $i \geq n$, $q_i > q$ -- or there is
another rational $q' < q$ such that $q_i < q'$ for all $i \in \NN$. The entries of the sequence get closer and
closer to a hole in the rational line, a hole where we would expect to find the irrational $\sqrt{2}$.

As it turns out, there are many such gaps in $\QQ$. We obtain the real numbers $\RR$ by filling in all of these
gaps, a process that is known as /completing/ the rationals. There are multiple ways to do this, and we describe
a few common ones below.

** Cauchy Sequences

The sequence of rationals we defined above had the interesting property that, although it seemed to approach a
single spot on the rational line, there was no rational number at that spot. We seek to formally capture this
idea of a "convergent" sequence without referring to a point that the sequence converges to.

We will approach this with the notion of a Cauchy sequence. Roughly speaking, a Cauchy sequence is one where the
entries become arbitrarily close, not just to their successors but to all following entries. More precisely:

--------
*Definition.* A sequence of rational numbers $\{q_i\}_{i \in \NN}$ is said to be /Cauchy/ if for every rational
number $\epsilon > 0$, there is some natural number $N \in \NN$ such that for all $i, j \geq N$, we have that
$|q_i - q_j| < \epsilon$.
--------

(It is common to use $\epsilon$ to represent a very small quantity.)

--------
*Lemma.* The sequence defined above to approximate $\sqrt{2}$ is Cauchy.

*Proof.* First, we note that if $i \leq j$, we know that $q_i \leq q_j$, and $q_j - q_i < \frac{1}{10^i}$. This
is true because $q_i$ and $q_j$ match through the $i$ th decimal place.

Let $\epsilon$ be an arbitrary rational number, and let $N$ be a natural number such that 
$\frac{1}{10^N} < \epsilon$. (Since $\epsilon > 0$, such an $N$ must exist.) Take $i$ and $j$ such that 
$i, j \geq N$, and suppose without loss of generality that $i \leq j$. Then 
\[ |q_i - q_j| = q_j - q_i < \frac{1}{10^i} \leq \frac{1}{10^N} < \epsilon. \]
--------

Cauchy sequences allow us to notice these gaps in the rationals, but they are not unique: many Cauchy sequences
can approach the same hole. For instance, the sequence $\{2, 1.5, 1.42, ...\}$ approaches the same point as
our other example, but from above instead of from below. It is slightly misleading to say that they "approach
the same point," since there is no rational point that they approach; a more precise statement is that the
sequences eventually become arbitrary close.

*Definition.* Two Cauchy sequences $p = \{p_i\}_{i \in \NN}$ and $q = \{q_i\}_{i \in \NN}$ are /equivalent/ if for every
rational number $\epsilon > 0$, there is some natural number $N \in \NN$ such that for all $i \geq N$, we have
that $|p_i - q_i| < \epsilon$. We write $p \sim q$.

As you might suspect from the name, $\sim$ defines an equivalence relation on Cauchy sequences. It is easy to check
reflexivity and symmetry; we leave it as an exercise to check transitivity. We also leave it as an exercise to 
show that the two approximations of $\sqrt{2}$ are equivalent.

Morally, two Cauchy sequences are eqivalent if they approach the same spot on the rational line. This spot may
be a gap, as in our example, or it may be a rational number: consider the Cauchy sequence $\{2, 2, 2, ...\}$.
The /equivalence class/ $[q]$ of a Cauchy sequence $q$ is the set of all Cauchy sequences that approach the same spot
as $q$. Any two distinct equivalence classes of Cauchy sequences approach different spots on the rational line.
But these spots on the rational line are precisely the real numbers, which include the rational numbers themselves
and the gaps in between. So we can define the real numbers to be 
\[ \RR = \{[q] \mid q\text{ is a Cauchy sequence of rational numbers}\}, \]
the set of equivalence classes of Cauchy sequences of rationals. This general move, going from a set $A$ to the
set of equivalence classes of elements of $A$, is called taking the /quotient/ of A. So the real numbers are the
quotient of the set of Cauchy sequences of rationals, with respect to Cauchy sequence equivalence.

Having the set $\RR$ by itself is not enough: we also would like to know how to add, subtract, multiply, and divide
real numbers. A common way to divide operations on quotient sets is to define them first on the original set, and
then show that the operation "respects" the equivalence relation. That is, we will say how to add Cauchy sequences
of rationals, and then show that if $p_1 \sim p_2$ and $q_1 \sim q_2$, then $p_1 + q_1 \sim p_2 + q_2$. We can then
lift this definition to $\RR$ by defining $[p] + [q]$ to be $[p + q]$.

Luckily, it is easy to define addition, subtraction, and multiplication on Cauchy sequences. If 
$p = \{p_i\}_{i \in \NN}$ and $q = \{q_i\}_{i \in \NN}$ are Cauchy sequences, let $p + q = \{p_i + q_i\}_{i \in \NN}
and similarly for subtraction and multiplication. It is trickier to show that these sequences are Cauchy themselves,
and to show that the operations have the appropriate algebraic properties. We walk through these arguments in a
series of exercises below.

Once we have lifted these operations to the quotient set $\RR$, we are basically finished. Our construction of $\RR$ 
looks and behaves just like we expect the real numbers to look and behave. However, thinking about Cauchy sequences
can be cumbersome, and we often want to abstract away from this kind of definition.

** An Algebraic Characterization

When we first introduced the natural numbers, we did so by describing an "interface" rather than a concrete
implementation. This allowed us to be modular in our implementation: Lean's version of natural numbers will look
somewhat different from the version in axiomatic set theory, but as long as they behave according to the same
higher-level rules, both structures will be the same in the relevant ways.

We can describe an interface for the real numbers in much the same way. Concisely, the real numbers are a complete
totally ordered field. Spelled out, this means:

- There are associative, commutative, and invertible binary operations $+$ and $*$ defined on $\RR$
- Multiplication distributes over addition: for all $x, y, z\in \RR$ we have $x*(y + z) = x*y + y*z$
- There are elements $0, 1 \in \RR$ that interact with addition and multiplication in the usual ways
- There is a total order $\leq$ defined on $\RR$
- For all $x, y, z \in \RR$, if $x \leq y$ then $x + z \leq y + z$
- For all $x, y \in \RR$, if $0 \leq x$ and $0 \leq y$ then $0 \leq x * y$
- Every Cauchy sequence of real numbers converges to a real number.

Notice that without this last property (completeness), the rational numbers would also meet this specification.

It is a fundamental algebraic result that these axioms characterize a unique structure. Any two models that meet
these requirements must behave in exactly the same way, at least insofar as the constants $0$ and $1$, the
operations $+$ and $*$, and the relation $\leq$ are concerned. This fact is hugely powerful because it allows us to
avoid thinking about the Cauchy sequence construction in normal mathematics. Once we have shown that our 
construction meets these requirements, we can take $\RR$ to be "the" unique complete totally ordered field and ignore
any implementation details. We are also free to implement $\RR$ in any way we choose, and as long as it meets this
interface, any theorems we prove about the reals will still apply.

** Dedekind Cuts

Many sources will use an alternative construction to of the Cauchy sequence method. This construction,
based on a definition known as a /Dedekind cut/, produces a structure that is (classically) identical.

A Dedekind cut is an ordered pair $\langle A, B \rangle$ of sets of rational numbers with the
following properties:

- Every rational number $q$ is in either $A$ or $B$.
- Each $a \in A$ is less than every $b \in B$.
- There is no greatest element of $A$.
- $A$ and $B$ are both nonempty.

The first two properties show why we call this pair a "cut." The set $A$ contains all of
the rational numbers to the left of some mark on the number line, and $B$ all of the points
to the right. The third property tells us something about what happens exactly at that mark.
But there are two possibilities: either $B$ has a least element, or it doesn't. Picturing
the situation where $A$ has no greatest element and $B$ has no least element may be tricky,
but consider the example $A = \{x \in \QQ : x^2 < 2\}$ and $B = \{x \in \QQ : x^2 > 2\}$.
There is no rational number $q$ such that $q^2 = 2$, but there are rational numbers on
either side that are arbitrarily close; thus neither $A$ nor $B$ contains an endpoint.

We define $\RR$ to be the set of Dedekind cuts. A Dedekind cut $\langle A, B \rangle$
corresponds to a rational number $q$ if $q$ is the least element of $B$, and to an irrational
number if $B$ has no least element. It is straightforward to define addition on $\RR$:
$$\langle A_1, B_1 \rangle + \langle A_2, B_2 \rangle = \langle \{a_1 + a_2 : a_1 \in A_1,
 a_2 \in A_2 \}, \{b_1 + b_2 : b_1 \in B_1, b_2 \in B_2 \} \rangle .$$
Multiplication is defined similarly.

Some authors prefer this construction to the Cauchy sequence construction because it avoids
taking the quotient of a set, and thus removes the complication of showing that arithmetic operations
respect equivalence. Others prefer Cauchy sequences since they provide a clearer notion
of approximation: if a real number $r$ is given by a Cauchy sequence $\{q_i\}_{i \in \NN}$,
then an arbitrarily close rational approximation of $r$ is given by $q_N$ for a sufficiently
high $N$. It is a matter of context, or sometimes personal taste, to decide which approach to use.

** Constructive Real Numbers

A strict constructivist would be upset by this claim about finding arbitrarily close rational
approximations. Suppose that $q = \{q_i\}_{i \in \NN}$ is a Cauchy sequence of rationals; for which
value $N$ is $q_N$ within $\frac{1}{10}$ of the corresponding real? The fact that $q$ is
Cauchy implies that there is some such $N$, but in general there is no way to compute what it is.
We could check 1000 terms and confirm that all are within $\frac{1}{100}$ of each other, but
the 1001st might jump up. The approximation is nonconstructive -- there is /some/ approximation
$q_N$, but we cannot compute what it is.

The Cauchy sequence construction looks somewhat different in constructive mathematics, in order
to ameliorate this kind of problem. Rather than calling a sequence Cauchy if it converges
/eventually/ (with no a priori information about when), we require that sequences converge at a
fixed rate.

------
*Definition.* A sequence of rationals $\{q_i\}_{i \in \NN}$ is /constructively Cauchy/ if for
all $i, j \in \NN$, we have that $|q_i - q_j| < \frac{1}{i + 1} + \frac{1}{j + 1}$.
------

It is not hard to see that every constructively Cauchy sequence is classically Cauchy. Furthermore,
if $\{q_i\}_{i \in \NN}$ is constructively Cauchy, it follows that $q_i$ is within $\frac{1}{i}$
of its corresponding real number, providing a computable approximation method.

However, there are still limitations to the constructive approach. For one, defining the 
arithmetic operations on constructive Cauchy sequences is more difficult. The classical approach
of adding the sequences piecewise fails, since two constructive Cauchy sequences could sum to
a non-Cauchy sequence. Defining division is 
