 
Title: Logic and Proof
#+Author: [[http://www.andrew.cmu.edu/user/avigad][Jeremy Avigad]], [[http://www.andrew.cmu.edu/user/rlewis1/][Robert Y. Lewis]],  [[http://www.contrib.andrew.cmu.edu/~fpv/][Floris van Doorn]]

* Real Numbers and Analysis
:PROPERTIES:
  :CUSTOM_ID: Real_Numbers_and_Analysis
:END:

Mathematicians often distinguish the /discrete/ from the /continuous/. The natural numbers and the integers 
fall into the former category. Roughly speaking, this is because there is "space" between any two distinct
integers: 0 and 1 are not equal, but there is no integer that falls between them. (The study of topology makes
this distinction more precise.)

The rational numbers are different. If $a$ and $b$ are distinct rationals with $a < b$, then we know that
$a < \frac{b - a}{2} < b$. Put another way, for any rational $a$, there must be another rational arbitrarily close
to $a$: for any $\epsilon \in \QQ$, there is a $b \in \QQ$ such that $|a - b| < \epsilon$. We say that the
rational numbers are /dense/.

Despite being dense, though, there are still "gaps" in the rationals. Recall that any finite decimal number 
(e.g. 3.141) is rational, and consider the (infinite) decimal representation of $\sqrt{2}$, 1.41421356.... Define
a sequence of rational numbers $\{q_i\}_{i \in \NN}$, such that $q_i$ includes the first $i+1$ digits of $\sqrt{2}$:
$q_0=1, q_1=1.4, q_2 = 1.41,$ and so on. This is an increasing sequence, and the distance between subsequent
entries in the sequence gets smaller as $i$ grows. Nonetheless, it has no /limit point/. For any rational number
$q$, either the sequence "crosses" $q$ -- there is some $n$ such that, for all $i \geq n$, $q_i > q$ -- or there is
another rational $q' < q$ such that $q_i < q'$ for all $i \in \NN$. The entries of the sequence get closer and
closer to a hole in the rational line, a hole where we would expect to find the irrational $\sqrt{2}$.

As it turns out, there are many such gaps in $\QQ$. We obtain the real numbers $\RR$ by filling in all of these
gaps, a process that is known as /completing/ the rationals. There are multiple ways to do this, and we describe
a few common ones here.

** Cauchy Sequences

The sequence of rationals we defined above had the interesting property that, although it seemed to approach a
single spot on the rational line, there was no rational number at that spot. We seek to formally capture this
idea of a "convergent" sequence without referring to a point that the sequence converges to.

We will approach this with the notion of a Cauchy sequence. Roughly speaking, a Cauchy sequence is one where the
entries become arbitrarily close, not just to their successors but to all following entries. More precisely:

*Definition.* A sequence of rational numbers $\{q_i\}_{i \in \NN}$ is said to be /Cauchy/ if for every rational
number $\epsilon > 0$, there is some natural number $N \in \NN$ such that for all $i, j \geq N$, we have that
$|q_i - q_j| < \epsilon$.

(It is common to use $\epsilon$ to represent a very small quantity.)

*Lemma.* The sequence defined above to approximate $\sqrt{2}$ is Cauchy.
*Proof.* First, we note that if $i \leq j$, we know that $q_i \leq q_j$, and $q_j - q_i < \frac{1}{10^i}$. This
is true because $q_i$ and $q_j$ match through the $i$th decimal place.

Let $\epsilon$ be an arbitrary rational number, and let $N$ be a natural number such that 
$\frac{1}{10^N} < \epsilon$. (Since $\epsilon > 0$, such an $N$ must exist.) Take $i$ and $j$ such that 
$i, j \geq N$, and suppose without loss of generality that $i \leq j$. Then 
$$|q_i - q_j| = q_j - q_i < \frac{1}{10^i} \leq \frac{1}{10^N} < \epsilon.$$

Cauchy sequences allow us to notice these gaps in the rationals, but they are not unique: many Cauchy sequences
can approach the same hole. For instance, the sequence $\{2, 1.5, 1.42, ...\}$ approaches the same point as
our other example, but from above instead of from below. It is slightly misleading to say that they "approach
the same point," since there is no rational point that they approach; a more precise statement is that the
sequences eventually become arbitrary close.

*Definition.* Two Cauchy sequences $\{p_i\}_{i \in \NN}$ and $\{q_i\}_{i \in \NN}$ are /equivalent/ if for every
rational number $\epsilon > 0$, there is some natural number $N \in \NN$ such that for all $i \geq N$, we have
that $|p_i - q_i| < \epsilon$.

As you might suspect from the name, this defines an equivalence relation on Cauchy sequences. It is easy to check
reflexivity and symmetry; we leave it as an exercise to check transitivity. We also leave it as an exercise to 
show that the two approximations of $\sqrt{2}$ are equivalent.

Morally, two Cauchy sequences are eqivalent if they approach the same spot on the rational line. This spot may
be a gap, as in our example, or it may be a rational number: consider the Cauchy sequence $\{2, 2, 2, ...\}$.
The /equivalence class/ $[q]$ of a Cauchy sequence $q$ is the set of all Cauchy sequences that approach the same spot
as $q$. Any two distinct equivalence classes of Cauchy sequences approach different spots on the rational line.
But these spots on the rational line are precisely the real numbers, which include the rational numbers themselves
and the gaps in between. So we can define the real numbers to be 
$$\RR = \{[q] \mid q\text{ is a Cauchy sequence of rational numbers}\},$$
the set of equivalence classes of Cauchy sequences of rationals.
